//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoCommon.proto
namespace com.sporger.server.proto.model
{
    [global::ProtoBuf.ProtoContract(Name=@"MessageType")]
    public enum MessageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_VALIDATE", Value=1)]
      LOGIN_VALIDATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_VALIDATE_RECONNECT", Value=2)]
      LOGIN_VALIDATE_RECONNECT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_BE_KICKED_OFF", Value=3)]
      NOTIFY_BE_KICKED_OFF = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_BIND_ACCOUNT", Value=4)]
      REQ_BIND_ACCOUNT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CITY_INFO", Value=50)]
      REQ_CITY_INFO = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ADVERTISEMENT_INFO", Value=81)]
      REQ_ADVERTISEMENT_INFO = 81,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHARACTER_ATTRIBUTE", Value=100)]
      CHARACTER_ATTRIBUTE = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_WEAR_EQUIP", Value=101)]
      REQ_WEAR_EQUIP = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_UNINSTALL_EQUIP", Value=102)]
      REQ_UNINSTALL_EQUIP = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHARACTER_CURRENCY", Value=103)]
      NOTIFY_CHARACTER_CURRENCY = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHARACTER_LEVEL_UP", Value=104)]
      NOTIFY_CHARACTER_LEVEL_UP = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CREATE_CHARACTER", Value=105)]
      REQ_CREATE_CHARACTER = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_WECHAT_INFO", Value=106)]
      REQ_PLAYER_WECHAT_INFO = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_EQUIP_ATTRS", Value=150)]
      REQ_EQUIP_ATTRS = 150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SELL_ITME", Value=151)]
      REQ_SELL_ITME = 151,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_USE_ITEM", Value=152)]
      REQ_USE_ITEM = 152,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_EQUIP_START_UP", Value=153)]
      REQ_EQUIP_START_UP = 153,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DRAW_REWARD", Value=154)]
      REQ_DRAW_REWARD = 154,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DAILY_MISSION_LIST", Value=200)]
      REQ_DAILY_MISSION_LIST = 200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DAILY_MISSION_REWARD", Value=201)]
      REQ_DAILY_MISSION_REWARD = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_TUTORIAL_INFO", Value=225)]
      REQ_TUTORIAL_INFO = 225,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SAVE_TUTORIAL", Value=226)]
      REQ_SAVE_TUTORIAL = 226,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SAVE_TRIGGER_TUTORIAL", Value=227)]
      REQ_SAVE_TRIGGER_TUTORIAL = 227,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SAVE_CAREER_PLOT", Value=228)]
      REQ_SAVE_CAREER_PLOT = 228,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_FRIENDS", Value=350)]
      REQ_PLAYER_FRIENDS = 350,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FRIEND_STATE", Value=351)]
      REQ_FRIEND_STATE = 351,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FRIEND_DETAILED", Value=352)]
      REQ_FRIEND_DETAILED = 352,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ATTENTION_PLAYER", Value=353)]
      REQ_ATTENTION_PLAYER = 353,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PLAYER_ATTENTION", Value=354)]
      NOTIFY_PLAYER_ATTENTION = 354,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_JOIN_GAME", Value=355)]
      REQ_JOIN_GAME = 355,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_VISIT_GAME", Value=356)]
      REQ_VISIT_GAME = 356,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FRIEND_MESSAGE", Value=357)]
      REQ_FRIEND_MESSAGE = 357,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DELECT_FRIEND_MESSAGE", Value=358)]
      REQ_DELECT_FRIEND_MESSAGE = 358,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FRIENDS_RELATION", Value=359)]
      REQ_FRIENDS_RELATION = 359,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SEARCH_PLAYER", Value=360)]
      REQ_SEARCH_PLAYER = 360,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_BASE_INFO", Value=361)]
      REQ_PLAYER_BASE_INFO = 361,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GIVE_PLAYER_THUMBS_UP", Value=362)]
      REQ_GIVE_PLAYER_THUMBS_UP = 362,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_HAVE_GIVE_PLAYER_THUMBS_UP", Value=363)]
      REQ_HAVE_GIVE_PLAYER_THUMBS_UP = 363,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_MAP", Value=400)]
      REQ_ENTER_MAP = 400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_MAP", Value=401)]
      ENTER_MAP = 401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_GOIN_INSTANCE", Value=402)]
      PLAYER_GOIN_INSTANCE = 402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_EXIT_INSTANCE", Value=403)]
      PLAYER_EXIT_INSTANCE = 403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYNC_PLAYER_INSTANCE_POS", Value=404)]
      SYNC_PLAYER_INSTANCE_POS = 404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SERVER_TIME", Value=405)]
      REQ_SERVER_TIME = 405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEARTBEAT", Value=406)]
      HEARTBEAT = 406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MATCHING", Value=407)]
      REQ_MATCHING = 407,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CANCEL_MATCHING", Value=408)]
      REQ_CANCEL_MATCHING = 408,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MATCHING_RESULT", Value=409)]
      NOTIFY_MATCHING_RESULT = 409,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_PRE_SCENE", Value=410)]
      REQ_ENTER_PRE_SCENE = 410,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PLAYER_READY_ENTER_PRE_SCENE", Value=411)]
      NOTIFY_PLAYER_READY_ENTER_PRE_SCENE = 411,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PERMITE_ENTER_PRE_SCENE", Value=412)]
      NOTIFY_PERMITE_ENTER_PRE_SCENE = 412,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SELECT_SCENE", Value=413)]
      REQ_SELECT_SCENE = 413,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHANGE_SCENE", Value=414)]
      NOTIFY_CHANGE_SCENE = 414,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_READY", Value=415)]
      REQ_READY = 415,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_READY", Value=416)]
      NOTIFY_READY = 416,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHANGE_ROOM_OWNER", Value=417)]
      NOTIFY_CHANGE_ROOM_OWNER = 417,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_START_RACE", Value=420)]
      NOTIFY_START_RACE = 420,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CAREER_RUN_END", Value=421)]
      NOTIFY_CAREER_RUN_END = 421,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FREE_RUN_END", Value=422)]
      REQ_FREE_RUN_END = 422,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PLAYER_REACH", Value=423)]
      NOTIFY_PLAYER_REACH = 423,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_OUTDOOR_PVP_RESULT", Value=424)]
      NOTIFY_OUTDOOR_PVP_RESULT = 424,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_ITEM_PVP_RESULT", Value=425)]
      NOTIFY_ITEM_PVP_RESULT = 425,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_LIST", Value=426)]
      REQ_PLAYER_LIST = 426,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_NEW_PLAYER_LIST_SIMPLE_INFO", Value=427)]
      REQ_NEW_PLAYER_LIST_SIMPLE_INFO = 427,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CONFIRM_MATCHING_TIME_OUT", Value=428)]
      NOTIFY_CONFIRM_MATCHING_TIME_OUT = 428,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_LEVEL_STAR_END", Value=429)]
      NOTIFY_LEVEL_STAR_END = 429,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_CAREER_MAP", Value=430)]
      REQ_ENTER_CAREER_MAP = 430,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FREE_RUN_PLAYER_START_RUN_TIME", Value=431)]
      REQ_FREE_RUN_PLAYER_START_RUN_TIME = 431,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FREE_RUN_PAUSE", Value=432)]
      REQ_FREE_RUN_PAUSE = 432,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FREE_RUN_RESUME", Value=433)]
      REQ_FREE_RUN_RESUME = 433,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_GOIN_INSTANCE", Value=434)]
      REQ_PLAYER_GOIN_INSTANCE = 434,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SYNC_PLAYER_INSTANCE_POS", Value=435)]
      REQ_SYNC_PLAYER_INSTANCE_POS = 435,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLYAER_EXIT_INSTANCE", Value=436)]
      REQ_PLYAER_EXIT_INSTANCE = 436,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FREE_RUN_INFO", Value=437)]
      REQ_FREE_RUN_INFO = 437,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_REALTIME_VOICE", Value=450)]
      REQ_REALTIME_VOICE = 450,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CANCEL_REALTIME_VOICE", Value=451)]
      REQ_CANCEL_REALTIME_VOICE = 451,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ACCEPT_REALTIME_VOICE", Value=452)]
      REQ_ACCEPT_REALTIME_VOICE = 452,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_HANGUP_REALTIME_VOICE", Value=453)]
      REQ_HANGUP_REALTIME_VOICE = 453,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_REALTIME_VOICE_REQ", Value=454)]
      NOTIFY_REALTIME_VOICE_REQ = 454,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_REALTIME_VOICE_REQ_FAILURE", Value=455)]
      NOTIFY_REALTIME_VOICE_REQ_FAILURE = 455,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PLAYER_JOIN_REALTIME_VOICE_ROOM", Value=456)]
      NOTIFY_PLAYER_JOIN_REALTIME_VOICE_ROOM = 456,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CANCEL_REALTIME_VOICE_REQ", Value=457)]
      NOTIFY_CANCEL_REALTIME_VOICE_REQ = 457,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PLAYER_LEAVE_REALTIME_VOICE_ROOM", Value=458)]
      NOTIFY_PLAYER_LEAVE_REALTIME_VOICE_ROOM = 458,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RUNNER_SEND_VOICE_MESSAGE", Value=461)]
      REQ_RUNNER_SEND_VOICE_MESSAGE = 461,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RUNNER_CONCERNED_VOICE_MESSAGE_LIST", Value=462)]
      REQ_RUNNER_CONCERNED_VOICE_MESSAGE_LIST = 462,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FANS_SEND_VOICE_MESSAGE", Value=463)]
      REQ_FANS_SEND_VOICE_MESSAGE = 463,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FANS_VOICE_MESSAGE_LIST", Value=464)]
      REQ_FANS_VOICE_MESSAGE_LIST = 464,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAP_VOICE_MESSAGE_LIST", Value=465)]
      REQ_MAP_VOICE_MESSAGE_LIST = 465,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_HOST_SEND_VOICE_MESSAGE", Value=466)]
      REQ_HOST_SEND_VOICE_MESSAGE = 466,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_FAM", Value=501)]
      REQ_ENTER_FAM = 501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_FAM_MAP", Value=502)]
      REQ_ENTER_FAM_MAP = 502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_OPEN_TREASURE_BOX", Value=503)]
      REQ_OPEN_TREASURE_BOX = 503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_BOX_AND_ITEM_LIST", Value=505)]
      NOTIFY_BOX_AND_ITEM_LIST = 505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_OPEN_TREASURE_BOX", Value=506)]
      NOTIFY_OPEN_TREASURE_BOX = 506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PICK_OPEN_TREASURE_BOX_ITEM", Value=507)]
      REQ_PICK_OPEN_TREASURE_BOX_ITEM = 507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PICK_OPEN_TREASURE_ITEM", Value=508)]
      NOTIFY_PICK_OPEN_TREASURE_ITEM = 508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DISCARD_OPEN_TREASURE_BOX_ITEM", Value=509)]
      REQ_DISCARD_OPEN_TREASURE_BOX_ITEM = 509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SPAWN_ORDINARY_BOX", Value=510)]
      NOTIFY_SPAWN_ORDINARY_BOX = 510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SPAWN_ITEM_AND_BOX", Value=511)]
      NOTIFY_SPAWN_ITEM_AND_BOX = 511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SPAWN_MP_ORDINARY_BOX", Value=512)]
      NOTIFY_SPAWN_MP_ORDINARY_BOX = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_OPEN_MP_ORDINARY_BOX_STAND_POS", Value=513)]
      NOTIFY_OPEN_MP_ORDINARY_BOX_STAND_POS = 513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RESTORE_MP_ORDINARY_BOX_STAND_POS", Value=514)]
      NOTIFY_RESTORE_MP_ORDINARY_BOX_STAND_POS = 514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ACTIVITY", Value=517)]
      REQ_ACTIVITY = 517,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_ACTIVITY_END", Value=518)]
      NOTIFY_ACTIVITY_END = 518,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAIN_ACTIVITY", Value=519)]
      REQ_MAIN_ACTIVITY = 519,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAZE_MATCHING", Value=551)]
      REQ_MAZE_MATCHING = 551,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_MATCHING_RESULT", Value=552)]
      NOTIFY_MAZE_MATCHING_RESULT = 552,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAZE_CANCEL_MATCHING", Value=553)]
      REQ_MAZE_CANCEL_MATCHING = 553,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_WAIT_COUNT_DOWN", Value=554)]
      NOTIFY_MAZE_WAIT_COUNT_DOWN = 554,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_START_GAME_COUNT_DOWN", Value=555)]
      NOTIFY_MAZE_START_GAME_COUNT_DOWN = 555,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_START_GAME", Value=556)]
      NOTIFY_MAZE_START_GAME = 556,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_PLAYER_NOT_ENOUGH", Value=557)]
      NOTIFY_MAZE_PLAYER_NOT_ENOUGH = 557,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAZE_DESTROY_DOOR", Value=558)]
      REQ_MAZE_DESTROY_DOOR = 558,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_DESTROY_DOOR", Value=559)]
      NOTIFY_MAZE_DESTROY_DOOR = 559,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_SPAWN_DOOR", Value=560)]
      NOTIFY_MAZE_SPAWN_DOOR = 560,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_FINISH_POINT", Value=562)]
      REQ_ENTER_FINISH_POINT = 562,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_FINISH_MAZE_GAME", Value=563)]
      NOTIFY_FINISH_MAZE_GAME = 563,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_CHARACTER_ENERGE", Value=564)]
      NOTIFY_MAZE_CHARACTER_ENERGE = 564,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAZE_PICK_ENERGE_ITEM", Value=565)]
      REQ_MAZE_PICK_ENERGE_ITEM = 565,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_SPAWN_ENERGE_ITEM", Value=566)]
      NOTIFY_MAZE_SPAWN_ENERGE_ITEM = 566,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_PICK_ENERGE_ITEM", Value=567)]
      NOTIFY_MAZE_PICK_ENERGE_ITEM = 567,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_WATCH_RACE_FINISHED", Value=601)]
      NOTIFY_WATCH_RACE_FINISHED = 601,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_SQUARE_MAP", Value=701)]
      REQ_ENTER_SQUARE_MAP = 701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_HOT_SQUARE_CHAT_GROUP", Value=702)]
      REQ_HOT_SQUARE_CHAT_GROUP = 702,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CREATE_SQUARE_CHAT_GROUP", Value=703)]
      REQ_CREATE_SQUARE_CHAT_GROUP = 703,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_ADVERTISEMENT", Value=704)]
      NOTIFY_ADVERTISEMENT = 704,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_SQUARE_CHAT_GROUP", Value=705)]
      REQ_ENTER_SQUARE_CHAT_GROUP = 705,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_ENTER_SQUARE_CHAT_GROUP", Value=706)]
      NOTIFY_ENTER_SQUARE_CHAT_GROUP = 706,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SQUARE_CHAT_INFO", Value=707)]
      REQ_SQUARE_CHAT_INFO = 707,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SQUARE_CHAT_INFO", Value=708)]
      NOTIFY_SQUARE_CHAT_INFO = 708,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CLOSE_SQUARE_CHAT_GROUP", Value=709)]
      REQ_CLOSE_SQUARE_CHAT_GROUP = 709,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_EXIT_SQUARE_CHAT_GROUP", Value=710)]
      REQ_EXIT_SQUARE_CHAT_GROUP = 710,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CLOSE_SQUARE_CHAT_GROUP", Value=711)]
      NOTIFY_CLOSE_SQUARE_CHAT_GROUP = 711,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_EXIT_SQUARE_CHAT_GROUP", Value=712)]
      NOTIFY_EXIT_SQUARE_CHAT_GROUP = 712,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SQUARE_INVITE_FRIEND", Value=713)]
      REQ_SQUARE_INVITE_FRIEND = 713,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SQUARE_INVITE_AGREE_FRIEND", Value=714)]
      REQ_SQUARE_INVITE_AGREE_FRIEND = 714,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SQUARE_INVITE_FRIEND", Value=715)]
      NOTIFY_SQUARE_INVITE_FRIEND = 715,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PLAYER_ENTER_SQUARE", Value=716)]
      NOTIFY_PLAYER_ENTER_SQUARE = 716,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON", Value=751)]
      REQ_MARATHON = 751,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_REGISTER_INFO", Value=752)]
      REQ_MARATHON_REGISTER_INFO = 752,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_PAY", Value=753)]
      REQ_MARATHON_PAY = 753,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_PROCEED_LIST", Value=754)]
      REQ_MARATHON_PROCEED_LIST = 754,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_HAVE_MARATHON_START", Value=755)]
      NOTIFY_HAVE_MARATHON_START = 755,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RAINBOWRUN_MATCHING", Value=801)]
      REQ_RAINBOWRUN_MATCHING = 801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_MATCHING_RESULT", Value=802)]
      NOTIFY_RAINBOWRUN_MATCHING_RESULT = 802,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RAINBOWRUN_CANCEL_MATCHING", Value=803)]
      REQ_RAINBOWRUN_CANCEL_MATCHING = 803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RAINBOWRUN_CHANGE_TRACK", Value=804)]
      REQ_RAINBOWRUN_CHANGE_TRACK = 804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_CHANGE_TRACK", Value=805)]
      NOTIFY_RAINBOWRUN_CHANGE_TRACK = 805,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_CURRENT_INFO", Value=806)]
      NOTIFY_RAINBOWRUN_CURRENT_INFO = 806,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_GAMEOVER", Value=807)]
      NOTIFY_RAINBOWRUN_GAMEOVER = 807,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RAINBOWRUN_READY", Value=808)]
      REQ_RAINBOWRUN_READY = 808,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_READY", Value=809)]
      NOTIFY_RAINBOWRUN_READY = 809,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_LOAD_SCENE", Value=810)]
      NOTIFY_RAINBOWRUN_LOAD_SCENE = 810,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_INVITE_FRIEND", Value=811)]
      REQ_INVITE_FRIEND = 811,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_AGREE_INVITE", Value=812)]
      REQ_AGREE_INVITE = 812,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_INVITE_FRIEND_ENTER", Value=813)]
      NOTIFY_INVITE_FRIEND_ENTER = 813,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RAINBOWRUN_CREATE_ROOM", Value=814)]
      REQ_RAINBOWRUN_CREATE_ROOM = 814,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_HAVE_INVITE_FRIEND", Value=815)]
      NOTIFY_HAVE_INVITE_FRIEND = 815,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_ENTER_INVITE_ROOM", Value=816)]
      NOTIFY_ENTER_INVITE_ROOM = 816,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SETTING_ROOM", Value=817)]
      REQ_SETTING_ROOM = 817,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SETTING_ROOM", Value=818)]
      NOTIFY_SETTING_ROOM = 818,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_BACK_INVITE_ROOM", Value=819)]
      NOTIFY_BACK_INVITE_ROOM = 819,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_TRACK_MAX_COLOR", Value=820)]
      NOTIFY_TRACK_MAX_COLOR = 820,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_MATCHING", Value=821)]
      NOTIFY_RAINBOWRUN_MATCHING = 821,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MARATHON_CURENT_INFO", Value=851)]
      NOTIFY_MARATHON_CURENT_INFO = 851,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MARATHON_GAMEOVER", Value=852)]
      NOTIFY_MARATHON_GAMEOVER = 852,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_MARATHON_MAP", Value=853)]
      REQ_ENTER_MARATHON_MAP = 853,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SEND_BULLET_SCREEN", Value=854)]
      REQ_SEND_BULLET_SCREEN = 854,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MARATHON_PLAYER_ENTER", Value=855)]
      NOTIFY_MARATHON_PLAYER_ENTER = 855,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_RECORD", Value=857)]
      REQ_MARATHON_RECORD = 857,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_BASE_RECORD", Value=858)]
      REQ_MARATHON_BASE_RECORD = 858,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_SEARCH_PLAYER", Value=859)]
      REQ_MARATHON_SEARCH_PLAYER = 859,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_STOP_WATCH_RACE", Value=860)]
      REQ_MARATHON_STOP_WATCH_RACE = 860,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_ENTER_WATCH_RACE_MODE", Value=861)]
      REQ_MARATHON_ENTER_WATCH_RACE_MODE = 861,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MARATHON_WATCHING_PLAYER_INFO", Value=862)]
      NOTIFY_MARATHON_WATCHING_PLAYER_INFO = 862,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MARATHON_CHANGE_WATCH_PLAYER", Value=863)]
      NOTIFY_MARATHON_CHANGE_WATCH_PLAYER = 863,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_WATCH_PLAYER", Value=864)]
      REQ_MARATHON_WATCH_PLAYER = 864,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MARATHON_WATCH_MODE_FINISH", Value=865)]
      NOTIFY_MARATHON_WATCH_MODE_FINISH = 865,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_CURENT_INFO", Value=866)]
      REQ_MARATHON_CURENT_INFO = 866,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_GAMEOVER", Value=867)]
      REQ_MARATHON_GAMEOVER = 867,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_PLAYER_ENTER", Value=868)]
      REQ_MARATHON_PLAYER_ENTER = 868,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_WATCHING_PLAYER_INFO", Value=869)]
      REQ_MARATHON_WATCHING_PLAYER_INFO = 869,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_WATCH_MODE_FINISH", Value=870)]
      REQ_MARATHON_WATCH_MODE_FINISH = 870,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_INFO", Value=871)]
      REQ_MARATHON_INFO = 871,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_RANK", Value=872)]
      REQ_MARATHON_RANK = 872,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_RANK_REWARD", Value=873)]
      REQ_MARATHON_RANK_REWARD = 873,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_HOT_RANK_INFO", Value=874)]
      REQ_MARATHON_HOT_RANK_INFO = 874,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_RECOMMEND_RUNNER", Value=875)]
      REQ_MARATHON_RECOMMEND_RUNNER = 875,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MARATHON_RANK_REWARD_LIST", Value=876)]
      REQ_MARATHON_RANK_REWARD_LIST = 876,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MATCH_PROCEED_LIST", Value=900)]
      REQ_MATCH_PROCEED_LIST = 900,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_MATCH_MAP", Value=901)]
      REQ_ENTER_MATCH_MAP = 901,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHAMPION_CURENT_INFO", Value=902)]
      NOTIFY_CHAMPION_CURENT_INFO = 902,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHAMPION_GAMEOVER", Value=903)]
      NOTIFY_CHAMPION_GAMEOVER = 903,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_HAVE_MATCH_START", Value=904)]
      NOTIFY_HAVE_MATCH_START = 904,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SEASON_RANK_LIST", Value=905)]
      REQ_SEASON_RANK_LIST = 905,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SEASON_PLAYER_LIST", Value=906)]
      REQ_SEASON_PLAYER_LIST = 906,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SEASON_START", Value=907)]
      NOTIFY_SEASON_START = 907,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SEASON_START", Value=908)]
      REQ_SEASON_START = 908,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_GRADE_CHANGE", Value=909)]
      NOTIFY_GRADE_CHANGE = 909,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SEASON_INTEGRAL", Value=910)]
      REQ_SEASON_INTEGRAL = 910,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_CAREER_PLAN_LIST", Value=926)]
      REQ_PLAYER_CAREER_PLAN_LIST = 926,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_CAREER_DAILY_PLAN", Value=927)]
      REQ_PLAYER_CAREER_DAILY_PLAN = 927,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_CAREER_PLAN_RECORD_LIST", Value=928)]
      REQ_PLAYER_CAREER_PLAN_RECORD_LIST = 928,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CHANGE_CAREER_PLAN", Value=929)]
      REQ_CHANGE_CAREER_PLAN = 929,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RESET_CAREER_DAILY_PLAN", Value=930)]
      REQ_RESET_CAREER_DAILY_PLAN = 930,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GET_CAREER_PLAN_REWARD", Value=932)]
      REQ_GET_CAREER_PLAN_REWARD = 932,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAIL_INFO", Value=951)]
      REQ_MAIL_INFO = 951,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_READ_MAIL", Value=952)]
      REQ_READ_MAIL = 952,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GET_MAIL_ITEMS", Value=953)]
      REQ_GET_MAIL_ITEMS = 953,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DELETE_MAIL", Value=954)]
      REQ_DELETE_MAIL = 954,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_NEW_MAIL", Value=955)]
      NOTIFY_NEW_MAIL = 955,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCATION", Value=999)]
      LOCATION = 999,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CHARACTER_STATUS", Value=1000)]
      REQ_CHARACTER_STATUS = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHARACTER_STATUS", Value=1001)]
      NOTIFY_CHARACTER_STATUS = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAZE_CHARACTER_STATUS", Value=1002)]
      REQ_MAZE_CHARACTER_STATUS = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CITY_CHARACTER_STATUS", Value=1003)]
      REQ_CITY_CHARACTER_STATUS = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RAINBOW_RUN_CHARACTER_STATUS", Value=1004)]
      REQ_RAINBOW_RUN_CHARACTER_STATUS = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_INTERACTION_RESULT", Value=2000)]
      REQ_INTERACTION_RESULT = 2000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_INTERACTION_RANK", Value=2001)]
      REQ_INTERACTION_RANK = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_INTERACTION", Value=2002)]
      REQ_INTERACTION = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_INTERACTION_SPECIFY_PLAYER", Value=2003)]
      REQ_INTERACTION_SPECIFY_PLAYER = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CHEER_LIST", Value=2101)]
      REQ_CHEER_LIST = 2101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GET_CHEER_GOODS", Value=2102)]
      REQ_GET_CHEER_GOODS = 2102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DELETE_CHEER", Value=2103)]
      REQ_DELETE_CHEER = 2103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHEER_REMIND", Value=2104)]
      NOTIFY_CHEER_REMIND = 2104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_OTHER_CHEER_LIST", Value=2105)]
      REQ_OTHER_CHEER_LIST = 2105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MARATHON_CHEER_PROGRESS", Value=2106)]
      NOTIFY_MARATHON_CHEER_PROGRESS = 2106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_CHEER_SHARE_INFO", Value=2107)]
      REQ_PLAYER_CHEER_SHARE_INFO = 2107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_CHEER_REWARD_INFO", Value=2108)]
      REQ_PLAYER_CHEER_REWARD_INFO = 2108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CONVERT_CHEER_REWARD", Value=2109)]
      REQ_CONVERT_CHEER_REWARD = 2109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CONFIRM_CONVERT_CHEER_REWARD", Value=2110)]
      REQ_CONFIRM_CONVERT_CHEER_REWARD = 2110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RUN_REPORT", Value=3000)]
      RUN_REPORT = 3000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RUN_BASE_INFO", Value=3001)]
      REQ_RUN_BASE_INFO = 3001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PULL_RUN_RECORD", Value=3002)]
      REQ_PULL_RUN_RECORD = 3002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RUN_BEST_RECORD_LIST", Value=3003)]
      REQ_RUN_BEST_RECORD_LIST = 3003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RUN_RECORD_DETAIL", Value=3004)]
      REQ_RUN_RECORD_DETAIL = 3004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SPORGER_CHANGE", Value=3005)]
      NOTIFY_SPORGER_CHANGE = 3005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_WARM_BODY_FINISH", Value=3006)]
      REQ_WARM_BODY_FINISH = 3006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RUN_REPORT", Value=3007)]
      NOTIFY_RUN_REPORT = 3007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_GET_REWARD", Value=5000)]
      NOTIFY_GET_REWARD = 5000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_GM_LEVELUP", Value=5001)]
      NOTIFY_GM_LEVELUP = 5001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_BULLET_SCREEN_TEXT", Value=5200)]
      NOTIFY_BULLET_SCREEN_TEXT = 5200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_REMIND", Value=5100)]
      REQ_REMIND = 5100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_REMIND", Value=5101)]
      NOTIFY_REMIND = 5101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_REMIND_LIST", Value=5102)]
      NOTIFY_REMIND_LIST = 5102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CONVERT_COIN", Value=5300)]
      REQ_CONVERT_COIN = 5300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GM_COMMAND", Value=10000)]
      REQ_GM_COMMAND = 10000
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerState")]
    public enum PlayerState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OFFLINE", Value=0)]
      OFFLINE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEISURE", Value=1)]
      LEISURE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPORTS", Value=2)]
      SPORTS = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AttentionState")]
    public enum AttentionState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONCERNED", Value=0)]
      CONCERNED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BECONCERNED", Value=1)]
      BECONCERNED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MUTUALCONCERNED", Value=2)]
      MUTUALCONCERNED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRANGER", Value=3)]
      STRANGER = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CharacterState")]
    public enum CharacterState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WALKING", Value=0)]
      WALKING = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIGGING", Value=1)]
      DIGGING = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PBPlatformType")]
    public enum PBPlatformType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WeChat", Value=1)]
      WeChat = 1
    }
  
}