//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoCheer.proto
// Note: requires additional types generated from: model/ProtoPlayer.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cheer_base_info")]
  public partial class cheer_base_info : global::ProtoBuf.IExtensible
  {
    public cheer_base_info() {}
    
    private uint _cheerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cheerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cheerId
    {
      get { return _cheerId; }
      set { _cheerId = value; }
    }
    private string _iconUrl;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"iconUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string iconUrl
    {
      get { return _iconUrl; }
      set { _iconUrl = value; }
    }
    private ulong _startTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private ulong _endTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private uint _itemLeftCount;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"itemLeftCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemLeftCount
    {
      get { return _itemLeftCount; }
      set { _itemLeftCount = value; }
    }
    private string _miniPath;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"miniPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string miniPath
    {
      get { return _miniPath; }
      set { _miniPath = value; }
    }
    private string _title;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _imageUrl;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"imageUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string imageUrl
    {
      get { return _imageUrl; }
      set { _imageUrl = value; }
    }
    private uint _miniProgramType;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"miniProgramType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint miniProgramType
    {
      get { return _miniProgramType; }
      set { _miniProgramType = value; }
    }
    private com.sporger.server.proto.model.cheer_goods_status _itemSate;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"itemSate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.sporger.server.proto.model.cheer_goods_status itemSate
    {
      get { return _itemSate; }
      set { _itemSate = value; }
    }
    private uint _needCheerPoint;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"needCheerPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint needCheerPoint
    {
      get { return _needCheerPoint; }
      set { _needCheerPoint = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_cheer_list_out")]
  public partial class req_cheer_list_out : global::ProtoBuf.IExtensible
  {
    public req_cheer_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_base_info> _infoList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_base_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"infoList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_base_info> infoList
    {
      get { return _infoList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_get_cheer_goods_in")]
  public partial class req_get_cheer_goods_in : global::ProtoBuf.IExtensible
  {
    public req_get_cheer_goods_in() {}
    
    private uint _cheerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cheerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cheerId
    {
      get { return _cheerId; }
      set { _cheerId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _PhoneNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"PhoneNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PhoneNum
    {
      get { return _PhoneNum; }
      set { _PhoneNum = value; }
    }
    private string _addr;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"addr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string addr
    {
      get { return _addr; }
      set { _addr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_get_cheer_goods_out")]
  public partial class req_get_cheer_goods_out : global::ProtoBuf.IExtensible
  {
    public req_get_cheer_goods_out() {}
    
    private com.sporger.server.proto.model.get_cheer_goods_result _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.sporger.server.proto.model.get_cheer_goods_result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _cheerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cheerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cheerId
    {
      get { return _cheerId; }
      set { _cheerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_delete_cheer_in")]
  public partial class req_delete_cheer_in : global::ProtoBuf.IExtensible
  {
    public req_delete_cheer_in() {}
    
    private uint _cheerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cheerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cheerId
    {
      get { return _cheerId; }
      set { _cheerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_delete_cheer_out")]
  public partial class req_delete_cheer_out : global::ProtoBuf.IExtensible
  {
    public req_delete_cheer_out() {}
    
    private uint _cheerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cheerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cheerId
    {
      get { return _cheerId; }
      set { _cheerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cheer_remind_info")]
  public partial class cheer_remind_info : global::ProtoBuf.IExtensible
  {
    public cheer_remind_info() {}
    
    private com.sporger.server.proto.model.cheer_remind_type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.sporger.server.proto.model.cheer_remind_type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _voiceId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"voiceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint voiceId
    {
      get { return _voiceId; }
      set { _voiceId = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_cheer_remind")]
  public partial class notify_cheer_remind : global::ProtoBuf.IExtensible
  {
    public notify_cheer_remind() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_remind_info> _remind = new global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_remind_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"remind", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_remind_info> remind
    {
      get { return _remind; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"other_cheer_info")]
  public partial class other_cheer_info : global::ProtoBuf.IExtensible
  {
    public other_cheer_info() {}
    
    private com.sporger.server.proto.model.player_simple_info _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_simple_info info
    {
      get { return _info; }
      set { _info = value; }
    }
    private uint _marathonBasicId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"marathonBasicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBasicId
    {
      get { return _marathonBasicId; }
      set { _marathonBasicId = value; }
    }
    private string _marathonName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"marathonName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string marathonName
    {
      get { return _marathonName; }
      set { _marathonName = value; }
    }
    private string _imgSrc;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"imgSrc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string imgSrc
    {
      get { return _imgSrc; }
      set { _imgSrc = value; }
    }
    private float _cheerProgress;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cheerProgress", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float cheerProgress
    {
      get { return _cheerProgress; }
      set { _cheerProgress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_other_cheer_list_in")]
  public partial class req_other_cheer_list_in : global::ProtoBuf.IExtensible
  {
    public req_other_cheer_list_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_other_cheer_list_out")]
  public partial class req_other_cheer_list_out : global::ProtoBuf.IExtensible
  {
    public req_other_cheer_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.other_cheer_info> _cheerInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.other_cheer_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cheerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.other_cheer_info> cheerInfo
    {
      get { return _cheerInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_marathon_cheer_progress_out")]
  public partial class notify_marathon_cheer_progress_out : global::ProtoBuf.IExtensible
  {
    public notify_marathon_cheer_progress_out() {}
    
    private float _watchPlayerProgress = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"watchPlayerProgress", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float watchPlayerProgress
    {
      get { return _watchPlayerProgress; }
      set { _watchPlayerProgress = value; }
    }
    private float _selfCheerProgress = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"selfCheerProgress", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float selfCheerProgress
    {
      get { return _selfCheerProgress; }
      set { _selfCheerProgress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_cheer_share_info_in")]
  public partial class req_player_cheer_share_info_in : global::ProtoBuf.IExtensible
  {
    public req_player_cheer_share_info_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_cheer_share_info_out")]
  public partial class req_player_cheer_share_info_out : global::ProtoBuf.IExtensible
  {
    public req_player_cheer_share_info_out() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _miniPath = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"miniPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string miniPath
    {
      get { return _miniPath; }
      set { _miniPath = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _imageUrl = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"imageUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string imageUrl
    {
      get { return _imageUrl; }
      set { _imageUrl = value; }
    }
    private uint _miniProgramType = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"miniProgramType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint miniProgramType
    {
      get { return _miniProgramType; }
      set { _miniProgramType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"convert_cheer_reward_record")]
  public partial class convert_cheer_reward_record : global::ProtoBuf.IExtensible
  {
    public convert_cheer_reward_record() {}
    
    private uint _recordId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"recordId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint recordId
    {
      get { return _recordId; }
      set { _recordId = value; }
    }
    private ulong _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _rewardName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rewardName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rewardName
    {
      get { return _rewardName; }
      set { _rewardName = value; }
    }
    private uint _costPoint;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"costPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint costPoint
    {
      get { return _costPoint; }
      set { _costPoint = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private string _rewardUnit = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rewardUnit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rewardUnit
    {
      get { return _rewardUnit; }
      set { _rewardUnit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_cheer_reward_info_in")]
  public partial class req_player_cheer_reward_info_in : global::ProtoBuf.IExtensible
  {
    public req_player_cheer_reward_info_in() {}
    
    private uint _marathonBasicId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonBasicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBasicId
    {
      get { return _marathonBasicId; }
      set { _marathonBasicId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_cheer_reward_info_out")]
  public partial class req_player_cheer_reward_info_out : global::ProtoBuf.IExtensible
  {
    public req_player_cheer_reward_info_out() {}
    
    private uint _cheerPoint;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cheerPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cheerPoint
    {
      get { return _cheerPoint; }
      set { _cheerPoint = value; }
    }
    private string _rewardName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rewardName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rewardName
    {
      get { return _rewardName; }
      set { _rewardName = value; }
    }
    private string _rewardIcon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rewardIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rewardIcon
    {
      get { return _rewardIcon; }
      set { _rewardIcon = value; }
    }
    private uint _cheerPerNeed;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"cheerPerNeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cheerPerNeed
    {
      get { return _cheerPerNeed; }
      set { _cheerPerNeed = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.convert_cheer_reward_record> _recordList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.convert_cheer_reward_record>();
    [global::ProtoBuf.ProtoMember(5, Name=@"recordList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.convert_cheer_reward_record> recordList
    {
      get { return _recordList; }
    }
  
    private string _rewardUnit = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"rewardUnit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rewardUnit
    {
      get { return _rewardUnit; }
      set { _rewardUnit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_convert_cheer_reward_in")]
  public partial class req_convert_cheer_reward_in : global::ProtoBuf.IExtensible
  {
    public req_convert_cheer_reward_in() {}
    
    private uint _marathonBasicId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonBasicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBasicId
    {
      get { return _marathonBasicId; }
      set { _marathonBasicId = value; }
    }
    private uint _cheerPoint;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cheerPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cheerPoint
    {
      get { return _cheerPoint; }
      set { _cheerPoint = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private string _rewardName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rewardName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rewardName
    {
      get { return _rewardName; }
      set { _rewardName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_convert_cheer_reward_out")]
  public partial class req_convert_cheer_reward_out : global::ProtoBuf.IExtensible
  {
    public req_convert_cheer_reward_out() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _marathonBasicId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"marathonBasicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBasicId
    {
      get { return _marathonBasicId; }
      set { _marathonBasicId = value; }
    }
    private com.sporger.server.proto.model.convert_cheer_reward_record _record = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"record", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.convert_cheer_reward_record record
    {
      get { return _record; }
      set { _record = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_confirm_convert_cheer_reward_in")]
  public partial class req_confirm_convert_cheer_reward_in : global::ProtoBuf.IExtensible
  {
    public req_confirm_convert_cheer_reward_in() {}
    
    private uint _recordId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"recordId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint recordId
    {
      get { return _recordId; }
      set { _recordId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_confirm_convert_cheer_reward_out")]
  public partial class req_confirm_convert_cheer_reward_out : global::ProtoBuf.IExtensible
  {
    public req_confirm_convert_cheer_reward_out() {}
    
    private uint _recordId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"recordId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint recordId
    {
      get { return _recordId; }
      set { _recordId = value; }
    }
    private uint _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"cheer_goods_status")]
    public enum cheer_goods_status
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DONTALLOW", Value=0)]
      DONTALLOW = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALLOWED", Value=1)]
      ALLOWED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HAVEGOT", Value=2)]
      HAVEGOT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHEERFAILURE", Value=3)]
      CHEERFAILURE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOLEFT", Value=4)]
      NOLEFT = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"get_cheer_goods_result")]
    public enum get_cheer_goods_result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GETFAILURE", Value=0)]
      GETFAILURE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GETSUCCESS", Value=1)]
      GETSUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHEERINVALID", Value=3)]
      CHEERINVALID = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"cheer_remind_type")]
    public enum cheer_remind_type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RecieveCheer", Value=1)]
      RecieveCheer = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CheerFinish", Value=2)]
      CheerFinish = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CheerProgress", Value=3)]
      CheerProgress = 3
    }
  
}