//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoInteraction.proto
// Note: requires additional types generated from: model/ProtoPlayer.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"interaction_rank")]
  public partial class interaction_rank : global::ProtoBuf.IExtensible
  {
    public interaction_rank() {}
    
    private uint _rank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private uint _point;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint point
    {
      get { return _point; }
      set { _point = value; }
    }
    private string _playerIcon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerIcon
    {
      get { return _playerIcon; }
      set { _playerIcon = value; }
    }
    private string _playerName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private string _playerId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_interaction_result_in")]
  public partial class req_interaction_result_in : global::ProtoBuf.IExtensible
  {
    public req_interaction_result_in() {}
    
    private uint _integral;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"integral", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint integral
    {
      get { return _integral; }
      set { _integral = value; }
    }
    private string _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _gameType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gameType
    {
      get { return _gameType; }
      set { _gameType = value; }
    }
    private uint _marathonBaseId = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"marathonBaseId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint marathonBaseId
    {
      get { return _marathonBaseId; }
      set { _marathonBaseId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_interaction_result_out")]
  public partial class req_interaction_result_out : global::ProtoBuf.IExtensible
  {
    public req_interaction_result_out() {}
    
    private uint _integral;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"integral", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint integral
    {
      get { return _integral; }
      set { _integral = value; }
    }
    private uint _point;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint point
    {
      get { return _point; }
      set { _point = value; }
    }
    private uint _grade;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private bool _breaking;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"breaking", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool breaking
    {
      get { return _breaking; }
      set { _breaking = value; }
    }
    private string _shareTitle;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"shareTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string shareTitle
    {
      get { return _shareTitle; }
      set { _shareTitle = value; }
    }
    private string _imageUrl;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"imageUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string imageUrl
    {
      get { return _imageUrl; }
      set { _imageUrl = value; }
    }
    private string _programPath;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"programPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string programPath
    {
      get { return _programPath; }
      set { _programPath = value; }
    }
    private uint _miniProgramType = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"miniProgramType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint miniProgramType
    {
      get { return _miniProgramType; }
      set { _miniProgramType = value; }
    }
    private uint _highPoint = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"highPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint highPoint
    {
      get { return _highPoint; }
      set { _highPoint = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _nickIcon = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"nickIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickIcon
    {
      get { return _nickIcon; }
      set { _nickIcon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_interaction_rank_in")]
  public partial class req_interaction_rank_in : global::ProtoBuf.IExtensible
  {
    public req_interaction_rank_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _taskAcceptId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"taskAcceptId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint taskAcceptId
    {
      get { return _taskAcceptId; }
      set { _taskAcceptId = value; }
    }
    private uint _marathonBaseId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"marathonBaseId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBaseId
    {
      get { return _marathonBaseId; }
      set { _marathonBaseId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_interaction_rank_out")]
  public partial class req_interaction_rank_out : global::ProtoBuf.IExtensible
  {
    public req_interaction_rank_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.interaction_rank> _list = new global::System.Collections.Generic.List<com.sporger.server.proto.model.interaction_rank>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.interaction_rank> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_interaction_in")]
  public partial class req_interaction_in : global::ProtoBuf.IExtensible
  {
    public req_interaction_in() {}
    
    private uint _marathonBaseId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonBaseId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBaseId
    {
      get { return _marathonBaseId; }
      set { _marathonBaseId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_interaction_out")]
  public partial class req_interaction_out : global::ProtoBuf.IExtensible
  {
    public req_interaction_out() {}
    
    private com.sporger.server.proto.model.req_interaction_result _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.sporger.server.proto.model.req_interaction_result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private com.sporger.server.proto.model.player_simple_info _targetPlayerInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetPlayerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.player_simple_info targetPlayerInfo
    {
      get { return _targetPlayerInfo; }
      set { _targetPlayerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_interaction_specify_player_in")]
  public partial class req_interaction_specify_player_in : global::ProtoBuf.IExtensible
  {
    public req_interaction_specify_player_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_interaction_specify_player_out")]
  public partial class req_interaction_specify_player_out : global::ProtoBuf.IExtensible
  {
    public req_interaction_specify_player_out() {}
    
    private com.sporger.server.proto.model.req_interaction_result _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.sporger.server.proto.model.req_interaction_result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private com.sporger.server.proto.model.player_simple_info _targetPlayerInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetPlayerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.player_simple_info targetPlayerInfo
    {
      get { return _targetPlayerInfo; }
      set { _targetPlayerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"req_interaction_result")]
    public enum req_interaction_result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ERROR", Value=1)]
      NO_ERROR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_IS_NOT_IN_RACE", Value=2)]
      PLAYER_IS_NOT_IN_RACE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_PLAYER_IN_RACE", Value=3)]
      NO_PLAYER_IN_RACE = 3
    }
  
}