//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoRedPoint.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_remind_list_out")]
  public partial class notify_remind_list_out : global::ProtoBuf.IExtensible
  {
    public notify_remind_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.remind_info> _remindInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.remind_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"remindInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.remind_info> remindInfo
    {
      get { return _remindInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"remind_info")]
  public partial class remind_info : global::ProtoBuf.IExtensible
  {
    public remind_info() {}
    
    private com.sporger.server.proto.model.RemindType _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.sporger.server.proto.model.RemindType id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _itemId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemId
    {
      get { return _itemId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_remind_in")]
  public partial class req_remind_in : global::ProtoBuf.IExtensible
  {
    public req_remind_in() {}
    
    private com.sporger.server.proto.model.remind_info _remindInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"remindInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.remind_info remindInfo
    {
      get { return _remindInfo; }
      set { _remindInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_remind_out")]
  public partial class req_remind_out : global::ProtoBuf.IExtensible
  {
    public req_remind_out() {}
    
    private com.sporger.server.proto.model.remind_info _remindInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"remindInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.remind_info remindInfo
    {
      get { return _remindInfo; }
      set { _remindInfo = value; }
    }
    private bool _remindShow;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"remindShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool remindShow
    {
      get { return _remindShow; }
      set { _remindShow = value; }
    }
    private bool _itemShow;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"itemShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool itemShow
    {
      get { return _itemShow; }
      set { _itemShow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_remind_out")]
  public partial class notify_remind_out : global::ProtoBuf.IExtensible
  {
    public notify_remind_out() {}
    
    private com.sporger.server.proto.model.remind_info _remindInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"remindInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.remind_info remindInfo
    {
      get { return _remindInfo; }
      set { _remindInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RemindType")]
    public enum RemindType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND", Value=1)]
      FRIEND = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILYMISSION", Value=2)]
      DAILYMISSION = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INFORMATION", Value=3)]
      INFORMATION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BAG", Value=4)]
      BAG = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RUNRECORD", Value=5)]
      RUNRECORD = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY", Value=6)]
      ACTIVITY = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL", Value=7)]
      MAIL = 7
    }
  
}