//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoAdvertisement.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_advertisement_info_in")]
  public partial class req_advertisement_info_in : global::ProtoBuf.IExtensible
  {
    public req_advertisement_info_in() {}
    
    private uint _advType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"advType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint advType
    {
      get { return _advType; }
      set { _advType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_advertisement_info_out")]
  public partial class req_advertisement_info_out : global::ProtoBuf.IExtensible
  {
    public req_advertisement_info_out() {}
    
    private uint _advType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"advType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint advType
    {
      get { return _advType; }
      set { _advType = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _url = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> url
    {
      get { return _url; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}