//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoCareerPlan.proto
// Note: requires additional types generated from: model/ProtoBag.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"career_plan_info")]
  public partial class career_plan_info : global::ProtoBuf.IExtensible
  {
    public career_plan_info() {}
    
    private uint _planId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint planId
    {
      get { return _planId; }
      set { _planId = value; }
    }
    private uint _allCal;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"allCal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint allCal
    {
      get { return _allCal; }
      set { _allCal = value; }
    }
    private uint _curDailyPlanId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"curDailyPlanId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint curDailyPlanId
    {
      get { return _curDailyPlanId; }
      set { _curDailyPlanId = value; }
    }
    private bool _isFinished;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isFinished", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFinished
    {
      get { return _isFinished; }
      set { _isFinished = value; }
    }
    private bool _isGetReward;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"isGetReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isGetReward
    {
      get { return _isGetReward; }
      set { _isGetReward = value; }
    }
    private bool _isCanChange;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"isCanChange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isCanChange
    {
      get { return _isCanChange; }
      set { _isCanChange = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"career_plan_record_info")]
  public partial class career_plan_record_info : global::ProtoBuf.IExtensible
  {
    public career_plan_record_info() {}
    
    private uint _planId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint planId
    {
      get { return _planId; }
      set { _planId = value; }
    }
    private uint _allCal;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"allCal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint allCal
    {
      get { return _allCal; }
      set { _allCal = value; }
    }
    private uint _time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _lastDailyPlanId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"lastDailyPlanId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastDailyPlanId
    {
      get { return _lastDailyPlanId; }
      set { _lastDailyPlanId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"career_daily_plan_info")]
  public partial class career_daily_plan_info : global::ProtoBuf.IExtensible
  {
    public career_daily_plan_info() {}
    
    private uint _dailyPlanId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dailyPlanId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dailyPlanId
    {
      get { return _dailyPlanId; }
      set { _dailyPlanId = value; }
    }
    private bool _isFinished;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isFinished", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFinished
    {
      get { return _isFinished; }
      set { _isFinished = value; }
    }
    private uint _spendTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"spendTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spendTime
    {
      get { return _spendTime; }
      set { _spendTime = value; }
    }
    private uint _averageSpeed;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"averageSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint averageSpeed
    {
      get { return _averageSpeed; }
      set { _averageSpeed = value; }
    }
    private uint _cal;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cal
    {
      get { return _cal; }
      set { _cal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_career_plan_list_out")]
  public partial class req_player_career_plan_list_out : global::ProtoBuf.IExtensible
  {
    public req_player_career_plan_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.career_plan_info> _curPlanList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.career_plan_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"curPlanList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.career_plan_info> curPlanList
    {
      get { return _curPlanList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_career_daily_plan_in")]
  public partial class req_player_career_daily_plan_in : global::ProtoBuf.IExtensible
  {
    public req_player_career_daily_plan_in() {}
    
    private uint _planId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint planId
    {
      get { return _planId; }
      set { _planId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_career_daily_plan_out")]
  public partial class req_player_career_daily_plan_out : global::ProtoBuf.IExtensible
  {
    public req_player_career_daily_plan_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.career_daily_plan_info> _dailyPlan = new global::System.Collections.Generic.List<com.sporger.server.proto.model.career_daily_plan_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"dailyPlan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.career_daily_plan_info> dailyPlan
    {
      get { return _dailyPlan; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_career_plan_record_list_in")]
  public partial class req_player_career_plan_record_list_in : global::ProtoBuf.IExtensible
  {
    public req_player_career_plan_record_list_in() {}
    
    private uint _planType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint planType
    {
      get { return _planType; }
      set { _planType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_career_plan_record_list_out")]
  public partial class req_player_career_plan_record_list_out : global::ProtoBuf.IExtensible
  {
    public req_player_career_plan_record_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.career_plan_record_info> _planRecordList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.career_plan_record_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"planRecordList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.career_plan_record_info> planRecordList
    {
      get { return _planRecordList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_change_career_plan_in")]
  public partial class req_change_career_plan_in : global::ProtoBuf.IExtensible
  {
    public req_change_career_plan_in() {}
    
    private uint _planId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint planId
    {
      get { return _planId; }
      set { _planId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_change_career_plan_out")]
  public partial class req_change_career_plan_out : global::ProtoBuf.IExtensible
  {
    public req_change_career_plan_out() {}
    
    private uint _planId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint planId
    {
      get { return _planId; }
      set { _planId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_reset_career_daily_plan_in")]
  public partial class req_reset_career_daily_plan_in : global::ProtoBuf.IExtensible
  {
    public req_reset_career_daily_plan_in() {}
    
    private uint _planId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint planId
    {
      get { return _planId; }
      set { _planId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_reset_career_daily_plan_out")]
  public partial class req_reset_career_daily_plan_out : global::ProtoBuf.IExtensible
  {
    public req_reset_career_daily_plan_out() {}
    
    private uint _planId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint planId
    {
      get { return _planId; }
      set { _planId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_get_career_plan_reward_in")]
  public partial class req_get_career_plan_reward_in : global::ProtoBuf.IExtensible
  {
    public req_get_career_plan_reward_in() {}
    
    private uint _planId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint planId
    {
      get { return _planId; }
      set { _planId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_get_career_plan_reward_out")]
  public partial class req_get_career_plan_reward_out : global::ProtoBuf.IExtensible
  {
    public req_get_career_plan_reward_out() {}
    
    private uint _planId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint planId
    {
      get { return _planId; }
      set { _planId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}