//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoMarathon.proto
// Note: requires additional types generated from: model/ProtoBag.proto
// Note: requires additional types generated from: model/ProtoPlayer.proto
// Note: requires additional types generated from: model/ProtoRunReport.proto
// Note: requires additional types generated from: model/ProtoChat.proto
// Note: requires additional types generated from: model/ProtoCheer.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_in")]
  public partial class req_marathon_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_out")]
  public partial class req_marathon_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_event_info> _list = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_event_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_event_info> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_have_marathon_start_out")]
  public partial class notify_have_marathon_start_out : global::ProtoBuf.IExtensible
  {
    public notify_have_marathon_start_out() {}
    
    private uint _marathonBasicId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonBasicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBasicId
    {
      get { return _marathonBasicId; }
      set { _marathonBasicId = value; }
    }
    private ulong _startTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_event_info")]
  public partial class marathon_event_info : global::ProtoBuf.IExtensible
  {
    public marathon_event_info() {}
    
    private uint _marathonBasicId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonBasicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBasicId
    {
      get { return _marathonBasicId; }
      set { _marathonBasicId = value; }
    }
    private string _marathonName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"marathonName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string marathonName
    {
      get { return _marathonName; }
      set { _marathonName = value; }
    }
    private string _imgSrc;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"imgSrc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string imgSrc
    {
      get { return _imgSrc; }
      set { _imgSrc = value; }
    }
    private ulong _signupEndTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"signupEndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong signupEndTime
    {
      get { return _signupEndTime; }
      set { _signupEndTime = value; }
    }
    private ulong _startRunTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"startRunTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong startRunTime
    {
      get { return _startRunTime; }
      set { _startRunTime = value; }
    }
    private uint _entranceTimeRange;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"entranceTimeRange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint entranceTimeRange
    {
      get { return _entranceTimeRange; }
      set { _entranceTimeRange = value; }
    }
    private ulong _endTime;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private uint _crowd;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"crowd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint crowd
    {
      get { return _crowd; }
      set { _crowd = value; }
    }
    private bool _isRegister;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"isRegister", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isRegister
    {
      get { return _isRegister; }
      set { _isRegister = value; }
    }
    private bool _isHot;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"isHot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isHot
    {
      get { return _isHot; }
      set { _isHot = value; }
    }
    private bool _isDummy;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"isDummy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isDummy
    {
      get { return _isDummy; }
      set { _isDummy = value; }
    }
    private bool _isReal;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"isReal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isReal
    {
      get { return _isReal; }
      set { _isReal = value; }
    }
    private uint _registerCount;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"registerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint registerCount
    {
      get { return _registerCount; }
      set { _registerCount = value; }
    }
    private bool _isRun;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"isRun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isRun
    {
      get { return _isRun; }
      set { _isRun = value; }
    }
    private uint _cheerNum = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"cheerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cheerNum
    {
      get { return _cheerNum; }
      set { _cheerNum = value; }
    }
    private bool _hasReward = default(bool);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"hasReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool hasReward
    {
      get { return _hasReward; }
      set { _hasReward = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _hostId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(17, Name=@"hostId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> hostId
    {
      get { return _hostId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_proceed_list_in")]
  public partial class req_marathon_proceed_list_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_proceed_list_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_proceed_list_out")]
  public partial class req_marathon_proceed_list_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_proceed_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_event_info> _list = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_event_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_event_info> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_marathon_count_down_out")]
  public partial class notify_marathon_count_down_out : global::ProtoBuf.IExtensible
  {
    public notify_marathon_count_down_out() {}
    
    private uint _sencondLeft;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sencondLeft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sencondLeft
    {
      get { return _sencondLeft; }
      set { _sencondLeft = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_curent_index")]
  public partial class marathon_curent_index : global::ProtoBuf.IExtensible
  {
    public marathon_curent_index() {}
    
    private string _nickName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private uint _distance;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private uint _useTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"useTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint useTime
    {
      get { return _useTime; }
      set { _useTime = value; }
    }
    private string _playerId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _nickIcon;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"nickIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickIcon
    {
      get { return _nickIcon; }
      set { _nickIcon = value; }
    }
    private uint _rank = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_marathon_curent_info_out")]
  public partial class notify_marathon_curent_info_out : global::ProtoBuf.IExtensible
  {
    public notify_marathon_curent_info_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index> _curInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index>();
    [global::ProtoBuf.ProtoMember(1, Name=@"curInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index> curInfo
    {
      get { return _curInfo; }
    }
  
    private uint _playerCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private uint _audienceCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"audienceCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint audienceCount
    {
      get { return _audienceCount; }
      set { _audienceCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_player_rank_info")]
  public partial class marathon_player_rank_info : global::ProtoBuf.IExtensible
  {
    public marathon_player_rank_info() {}
    
    private uint _rankId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rankId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankId
    {
      get { return _rankId; }
      set { _rankId = value; }
    }
    private string _number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string number
    {
      get { return _number; }
      set { _number = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private uint _finishTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"finishTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint finishTime
    {
      get { return _finishTime; }
      set { _finishTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_marathon_gameover_out")]
  public partial class notify_marathon_gameover_out : global::ProtoBuf.IExtensible
  {
    public notify_marathon_gameover_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info> _rewards = new global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info> rewards
    {
      get { return _rewards; }
    }
  
    private com.sporger.server.proto.model.run_report_in _runInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"runInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.run_report_in runInfo
    {
      get { return _runInfo; }
      set { _runInfo = value; }
    }
    private uint _rank;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private bool _isFinished;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isFinished", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFinished
    {
      get { return _isFinished; }
      set { _isFinished = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_marathon_map_in")]
  public partial class req_enter_marathon_map_in : global::ProtoBuf.IExtensible
  {
    public req_enter_marathon_map_in() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_marathon_map_out")]
  public partial class req_enter_marathon_map_out : global::ProtoBuf.IExtensible
  {
    public req_enter_marathon_map_out() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private ulong _roomId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _distance = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private uint _eventType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private string _scenePath;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"scenePath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string scenePath
    {
      get { return _scenePath; }
      set { _scenePath = value; }
    }
    private string _prefabPath;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"prefabPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string prefabPath
    {
      get { return _prefabPath; }
      set { _prefabPath = value; }
    }
    private com.sporger.server.proto.model.marathon_event_info _currentMarathon;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"currentMarathon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.marathon_event_info currentMarathon
    {
      get { return _currentMarathon; }
      set { _currentMarathon = value; }
    }
    private string _marathonDetailName = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"marathonDetailName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string marathonDetailName
    {
      get { return _marathonDetailName; }
      set { _marathonDetailName = value; }
    }
    private uint _marathonDistance = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"marathonDistance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint marathonDistance
    {
      get { return _marathonDistance; }
      set { _marathonDistance = value; }
    }
    private uint _suit = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"suit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint suit
    {
      get { return _suit; }
      set { _suit = value; }
    }
    private float _useTime = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"useTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float useTime
    {
      get { return _useTime; }
      set { _useTime = value; }
    }
    private uint _step = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint step
    {
      get { return _step; }
      set { _step = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_player_info")]
  public partial class marathon_player_info : global::ProtoBuf.IExtensible
  {
    public marathon_player_info() {}
    
    private com.sporger.server.proto.model.player_simple_info _playerInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_simple_info playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private int _eventType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_marathon_player_enter_out")]
  public partial class notify_marathon_player_enter_out : global::ProtoBuf.IExtensible
  {
    public notify_marathon_player_enter_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_info> _playerList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_info> playerList
    {
      get { return _playerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_record_in")]
  public partial class req_marathon_record_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_record_in() {}
    
    private uint _marathonBasicId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonBasicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBasicId
    {
      get { return _marathonBasicId; }
      set { _marathonBasicId = value; }
    }
    private uint _marathonId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"marathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonId
    {
      get { return _marathonId; }
      set { _marathonId = value; }
    }
    private uint _page;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint page
    {
      get { return _page; }
      set { _page = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_record_out")]
  public partial class req_marathon_record_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_record_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_rank_info> _rankInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_rank_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rankInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_rank_info> rankInfo
    {
      get { return _rankInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_record_page_info")]
  public partial class marathon_record_page_info : global::ProtoBuf.IExtensible
  {
    public marathon_record_page_info() {}
    
    private uint _marathonId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonId
    {
      get { return _marathonId; }
      set { _marathonId = value; }
    }
    private uint _allPage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"allPage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint allPage
    {
      get { return _allPage; }
      set { _allPage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_base_record_in")]
  public partial class req_marathon_base_record_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_base_record_in() {}
    
    private uint _marathonBasicId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonBasicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBasicId
    {
      get { return _marathonBasicId; }
      set { _marathonBasicId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_base_record_out")]
  public partial class req_marathon_base_record_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_base_record_out() {}
    
    private com.sporger.server.proto.model.marathon_player_rank_info _playerRankInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerRankInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.marathon_player_rank_info playerRankInfo
    {
      get { return _playerRankInfo; }
      set { _playerRankInfo = value; }
    }
    private uint _marathonId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"marathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonId
    {
      get { return _marathonId; }
      set { _marathonId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_record_page_info> _pageInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_record_page_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"pageInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_record_page_info> pageInfo
    {
      get { return _pageInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_player_running_info")]
  public partial class marathon_player_running_info : global::ProtoBuf.IExtensible
  {
    public marathon_player_running_info() {}
    
    private uint _distance;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private uint _useTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"useTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint useTime
    {
      get { return _useTime; }
      set { _useTime = value; }
    }
    private uint _index;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private uint _eventType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_search_info")]
  public partial class marathon_search_info : global::ProtoBuf.IExtensible
  {
    public marathon_search_info() {}
    
    private com.sporger.server.proto.model.player_simple_info _baseInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"baseInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_simple_info baseInfo
    {
      get { return _baseInfo; }
      set { _baseInfo = value; }
    }
    private string _number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string number
    {
      get { return _number; }
      set { _number = value; }
    }
    private bool _hasAttention;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hasAttention", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool hasAttention
    {
      get { return _hasAttention; }
      set { _hasAttention = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_search_player_in")]
  public partial class req_marathon_search_player_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_search_player_in() {}
    
    private string _inputValue;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"inputValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string inputValue
    {
      get { return _inputValue; }
      set { _inputValue = value; }
    }
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_search_player_out")]
  public partial class req_marathon_search_player_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_search_player_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_search_info> _player = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_search_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_search_info> player
    {
      get { return _player; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_enter_watch_race_mode_in")]
  public partial class req_marathon_enter_watch_race_mode_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_enter_watch_race_mode_in() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_enter_watch_race_mode_out")]
  public partial class req_marathon_enter_watch_race_mode_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_enter_watch_race_mode_out() {}
    
    private com.sporger.server.proto.model.watch_marathon_result _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.sporger.server.proto.model.watch_marathon_result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _scenePath;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"scenePath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string scenePath
    {
      get { return _scenePath; }
      set { _scenePath = value; }
    }
    private string _prefabPath;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"prefabPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string prefabPath
    {
      get { return _prefabPath; }
      set { _prefabPath = value; }
    }
    private com.sporger.server.proto.model.marathon_event_info _currentMarathon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"currentMarathon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.marathon_event_info currentMarathon
    {
      get { return _currentMarathon; }
      set { _currentMarathon = value; }
    }
    private uint _curMarathonId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"curMarathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint curMarathonId
    {
      get { return _curMarathonId; }
      set { _curMarathonId = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_marathon_watching_player_info_out")]
  public partial class notify_marathon_watching_player_info_out : global::ProtoBuf.IExtensible
  {
    public notify_marathon_watching_player_info_out() {}
    
    private uint _distance;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private uint _useTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"useTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint useTime
    {
      get { return _useTime; }
      set { _useTime = value; }
    }
    private uint _index;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private uint _playerCount;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private uint _audienceCount;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"audienceCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint audienceCount
    {
      get { return _audienceCount; }
      set { _audienceCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_marathon_change_watch_player_out")]
  public partial class notify_marathon_change_watch_player_out : global::ProtoBuf.IExtensible
  {
    public notify_marathon_change_watch_player_out() {}
    
    private com.sporger.server.proto.model.watch_marathon_result _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.sporger.server.proto.model.watch_marathon_result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private com.sporger.server.proto.model.player_simple_info _tarPlayerInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tarPlayerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.player_simple_info tarPlayerInfo
    {
      get { return _tarPlayerInfo; }
      set { _tarPlayerInfo = value; }
    }
    private com.sporger.server.proto.model.marathon_player_running_info _tarPlayerRunningInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tarPlayerRunningInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.marathon_player_running_info tarPlayerRunningInfo
    {
      get { return _tarPlayerRunningInfo; }
      set { _tarPlayerRunningInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_watch_player_in")]
  public partial class req_marathon_watch_player_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_watch_player_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_watch_player_out")]
  public partial class req_marathon_watch_player_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_watch_player_out() {}
    
    private com.sporger.server.proto.model.marathon_player_status _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.sporger.server.proto.model.marathon_player_status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private com.sporger.server.proto.model.player_simple_info _tarPlayerInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tarPlayerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.player_simple_info tarPlayerInfo
    {
      get { return _tarPlayerInfo; }
      set { _tarPlayerInfo = value; }
    }
    private com.sporger.server.proto.model.marathon_player_running_info _runningInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"runningInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.marathon_player_running_info runningInfo
    {
      get { return _runningInfo; }
      set { _runningInfo = value; }
    }
    private uint _taskAcceptId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"taskAcceptId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint taskAcceptId
    {
      get { return _taskAcceptId; }
      set { _taskAcceptId = value; }
    }
    private string _marathonName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"marathonName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string marathonName
    {
      get { return _marathonName; }
      set { _marathonName = value; }
    }
    private uint _marathonDistance;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"marathonDistance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonDistance
    {
      get { return _marathonDistance; }
      set { _marathonDistance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_stop_marathon_watch_race_in")]
  public partial class req_stop_marathon_watch_race_in : global::ProtoBuf.IExtensible
  {
    public req_stop_marathon_watch_race_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_watch_mode_result_info")]
  public partial class marathon_watch_mode_result_info : global::ProtoBuf.IExtensible
  {
    public marathon_watch_mode_result_info() {}
    
    private uint _marathonId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonId
    {
      get { return _marathonId; }
      set { _marathonId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_rank_info> _rankInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_rank_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rankInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_rank_info> rankInfo
    {
      get { return _rankInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_marathon_watch_mode_finish_out")]
  public partial class notify_marathon_watch_mode_finish_out : global::ProtoBuf.IExtensible
  {
    public notify_marathon_watch_mode_finish_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_watch_mode_result_info> _resultList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_watch_mode_result_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"resultList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_watch_mode_result_info> resultList
    {
      get { return _resultList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_curent_info_in")]
  public partial class req_marathon_curent_info_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_curent_info_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_curent_info_out")]
  public partial class req_marathon_curent_info_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_curent_info_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index> _curInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index>();
    [global::ProtoBuf.ProtoMember(1, Name=@"curInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index> curInfo
    {
      get { return _curInfo; }
    }
  
    private uint _playerCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private uint _audienceCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"audienceCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint audienceCount
    {
      get { return _audienceCount; }
      set { _audienceCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_gameover_in")]
  public partial class req_marathon_gameover_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_gameover_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_gameover_out")]
  public partial class req_marathon_gameover_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_gameover_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info> _rewards = new global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info> rewards
    {
      get { return _rewards; }
    }
  
    private com.sporger.server.proto.model.run_report_in _runInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"runInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.run_report_in runInfo
    {
      get { return _runInfo; }
      set { _runInfo = value; }
    }
    private uint _rank;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private bool _isFinished;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isFinished", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFinished
    {
      get { return _isFinished; }
      set { _isFinished = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_player_enter_in")]
  public partial class req_marathon_player_enter_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_player_enter_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_player_enter_out")]
  public partial class req_marathon_player_enter_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_player_enter_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_info> _playerList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_info> playerList
    {
      get { return _playerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_watching_player_info_in")]
  public partial class req_marathon_watching_player_info_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_watching_player_info_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_watching_player_info_out")]
  public partial class req_marathon_watching_player_info_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_watching_player_info_out() {}
    
    private uint _distance;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private uint _useTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"useTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint useTime
    {
      get { return _useTime; }
      set { _useTime = value; }
    }
    private uint _index;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private uint _playerCount;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private uint _audienceCount;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"audienceCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint audienceCount
    {
      get { return _audienceCount; }
      set { _audienceCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_watch_mode_finish_in")]
  public partial class req_marathon_watch_mode_finish_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_watch_mode_finish_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_watch_mode_finish_out")]
  public partial class req_marathon_watch_mode_finish_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_watch_mode_finish_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_watch_mode_result_info> _resultList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_watch_mode_result_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"resultList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_watch_mode_result_info> resultList
    {
      get { return _resultList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_curent_info")]
  public partial class marathon_curent_info : global::ProtoBuf.IExtensible
  {
    public marathon_curent_info() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index> _curInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index>();
    [global::ProtoBuf.ProtoMember(1, Name=@"curInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index> curInfo
    {
      get { return _curInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_watching_player_info")]
  public partial class marathon_watching_player_info : global::ProtoBuf.IExtensible
  {
    public marathon_watching_player_info() {}
    
    private uint _distance;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private uint _useTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"useTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint useTime
    {
      get { return _useTime; }
      set { _useTime = value; }
    }
    private uint _index;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_gameover")]
  public partial class marathon_gameover : global::ProtoBuf.IExtensible
  {
    public marathon_gameover() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info> _rewards = new global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info> rewards
    {
      get { return _rewards; }
    }
  
    private com.sporger.server.proto.model.run_report_in _runInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"runInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.run_report_in runInfo
    {
      get { return _runInfo; }
      set { _runInfo = value; }
    }
    private uint _rank;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private bool _isFinished;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isFinished", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFinished
    {
      get { return _isFinished; }
      set { _isFinished = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"thumbs_up_player_info")]
  public partial class thumbs_up_player_info : global::ProtoBuf.IExtensible
  {
    public thumbs_up_player_info() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _playerName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private string _headIcon;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"headIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headIcon
    {
      get { return _headIcon; }
      set { _headIcon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_cheer_rank_info")]
  public partial class marathon_cheer_rank_info : global::ProtoBuf.IExtensible
  {
    public marathon_cheer_rank_info() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _playerName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private string _headIcon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"headIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headIcon
    {
      get { return _headIcon; }
      set { _headIcon = value; }
    }
    private uint _point;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint point
    {
      get { return _point; }
      set { _point = value; }
    }
    private uint _rank;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_run_base_info")]
  public partial class marathon_run_base_info : global::ProtoBuf.IExtensible
  {
    public marathon_run_base_info() {}
    
    private uint _playerCount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private uint _audienceCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"audienceCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint audienceCount
    {
      get { return _audienceCount; }
      set { _audienceCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_info_in")]
  public partial class req_marathon_info_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_info_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private bool _isRunner;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isRunner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isRunner
    {
      get { return _isRunner; }
      set { _isRunner = value; }
    }
    private uint _curMarathonId = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"curMarathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curMarathonId
    {
      get { return _curMarathonId; }
      set { _curMarathonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_info_out")]
  public partial class req_marathon_info_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_info_out() {}
    
    private com.sporger.server.proto.model.marathon_curent_info _currentInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"currentInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.marathon_curent_info currentInfo
    {
      get { return _currentInfo; }
      set { _currentInfo = value; }
    }
    private com.sporger.server.proto.model.marathon_watching_player_info _wathedInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"wathedInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.marathon_watching_player_info wathedInfo
    {
      get { return _wathedInfo; }
      set { _wathedInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_info> _playerList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_player_info> playerList
    {
      get { return _playerList; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_instance_syncinfo> _playersPosInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_instance_syncinfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"playersPosInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_instance_syncinfo> playersPosInfo
    {
      get { return _playersPosInfo; }
    }
  
    private com.sporger.server.proto.model.marathon_gameover _result = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.marathon_gameover result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.thumbs_up_player_info> _thumbsUpPlayer = new global::System.Collections.Generic.List<com.sporger.server.proto.model.thumbs_up_player_info>();
    [global::ProtoBuf.ProtoMember(6, Name=@"thumbsUpPlayer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.thumbs_up_player_info> thumbsUpPlayer
    {
      get { return _thumbsUpPlayer; }
    }
  
    private com.sporger.server.proto.model.voice_message_base_info _fansVoice = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fansVoice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.voice_message_base_info fansVoice
    {
      get { return _fansVoice; }
      set { _fansVoice = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_remind_info> _remind = new global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_remind_info>();
    [global::ProtoBuf.ProtoMember(8, Name=@"remind", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_remind_info> remind
    {
      get { return _remind; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _bulletScreenList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(9, Name=@"bulletScreenList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> bulletScreenList
    {
      get { return _bulletScreenList; }
    }
  
    private com.sporger.server.proto.model.marathon_run_base_info _baseInfo = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"baseInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.marathon_run_base_info baseInfo
    {
      get { return _baseInfo; }
      set { _baseInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index> _concernedPlayer = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index>();
    [global::ProtoBuf.ProtoMember(11, Name=@"concernedPlayer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index> concernedPlayer
    {
      get { return _concernedPlayer; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _playerOut = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(12, Name=@"playerOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> playerOut
    {
      get { return _playerOut; }
    }
  
    private com.sporger.server.proto.model.voice_message_base_info _runnerResponse = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"runnerResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.voice_message_base_info runnerResponse
    {
      get { return _runnerResponse; }
      set { _runnerResponse = value; }
    }
    private com.sporger.server.proto.model.voice_message_base_info _hostVoiceMessage = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"hostVoiceMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.voice_message_base_info hostVoiceMessage
    {
      get { return _hostVoiceMessage; }
      set { _hostVoiceMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_rank_base_info")]
  public partial class marathon_rank_base_info : global::ProtoBuf.IExtensible
  {
    public marathon_rank_base_info() {}
    
    private uint _rank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _playerId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _nickIcon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"nickIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickIcon
    {
      get { return _nickIcon; }
      set { _nickIcon = value; }
    }
    private ulong _spentTime = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"spentTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong spentTime
    {
      get { return _spentTime; }
      set { _spentTime = value; }
    }
    private uint _distance = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private uint _cheerPoint = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"cheerPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cheerPoint
    {
      get { return _cheerPoint; }
      set { _cheerPoint = value; }
    }
    private string _rewardItem = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"rewardItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rewardItem
    {
      get { return _rewardItem; }
      set { _rewardItem = value; }
    }
    private uint _rewardState = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"rewardState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rewardState
    {
      get { return _rewardState; }
      set { _rewardState = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_rank_in")]
  public partial class req_marathon_rank_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_rank_in() {}
    
    private uint _rankType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankType
    {
      get { return _rankType; }
      set { _rankType = value; }
    }
    private uint _marathonBasicId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"marathonBasicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBasicId
    {
      get { return _marathonBasicId; }
      set { _marathonBasicId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_rank_out")]
  public partial class req_marathon_rank_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_rank_out() {}
    
    private uint _rankType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankType
    {
      get { return _rankType; }
      set { _rankType = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_rank_base_info> _rankInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_rank_base_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rankInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_rank_base_info> rankInfo
    {
      get { return _rankInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_get_marathon_rank_reward_in")]
  public partial class req_get_marathon_rank_reward_in : global::ProtoBuf.IExtensible
  {
    public req_get_marathon_rank_reward_in() {}
    
    private uint _marathonBasicId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonBasicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonBasicId
    {
      get { return _marathonBasicId; }
      set { _marathonBasicId = value; }
    }
    private uint _rank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _phoneNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"phoneNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string phoneNum
    {
      get { return _phoneNum; }
      set { _phoneNum = value; }
    }
    private string _addr;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"addr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string addr
    {
      get { return _addr; }
      set { _addr = value; }
    }
    private string _suggestions;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"suggestions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string suggestions
    {
      get { return _suggestions; }
      set { _suggestions = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_rank_reward_out")]
  public partial class req_marathon_rank_reward_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_rank_reward_out() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_hot_rank_info_in")]
  public partial class req_marathon_hot_rank_info_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_hot_rank_info_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private bool _isRunner;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isRunner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isRunner
    {
      get { return _isRunner; }
      set { _isRunner = value; }
    }
    private uint _curMarathonId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"curMarathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint curMarathonId
    {
      get { return _curMarathonId; }
      set { _curMarathonId = value; }
    }
    private string _playerId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_hot_rank_info_out")]
  public partial class req_marathon_hot_rank_info_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_hot_rank_info_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_cheer_rank_info> _hotRank = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_cheer_rank_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"hotRank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_cheer_rank_info> hotRank
    {
      get { return _hotRank; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_cheer_rank_info> _fansCheerRank = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_cheer_rank_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"fansCheerRank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_cheer_rank_info> fansCheerRank
    {
      get { return _fansCheerRank; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_recommend_runner_in")]
  public partial class req_marathon_recommend_runner_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_recommend_runner_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _curMarathonId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"curMarathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint curMarathonId
    {
      get { return _curMarathonId; }
      set { _curMarathonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_recommend_runner_out")]
  public partial class req_marathon_recommend_runner_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_recommend_runner_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index> _recommendRunner = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index>();
    [global::ProtoBuf.ProtoMember(1, Name=@"recommendRunner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_curent_index> recommendRunner
    {
      get { return _recommendRunner; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"marathon_rank_reward")]
  public partial class marathon_rank_reward : global::ProtoBuf.IExtensible
  {
    public marathon_rank_reward() {}
    
    private string _rank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private string _reward;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_rank_reward_list_in")]
  public partial class req_marathon_rank_reward_list_in : global::ProtoBuf.IExtensible
  {
    public req_marathon_rank_reward_list_in() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_marathon_rank_reward_list_out")]
  public partial class req_marathon_rank_reward_list_out : global::ProtoBuf.IExtensible
  {
    public req_marathon_rank_reward_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_rank_reward> _reward = new global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_rank_reward>();
    [global::ProtoBuf.ProtoMember(1, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.marathon_rank_reward> reward
    {
      get { return _reward; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"marathon_player_status")]
    public enum marathon_player_status
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RUNNING", Value=0)]
      RUNNING = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ABSENCE", Value=1)]
      ABSENCE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FINISHED", Value=2)]
      FINISHED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID", Value=3)]
      INVALID = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"watch_marathon_result")]
    public enum watch_marathon_result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOERROR", Value=0)]
      NOERROR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOBODY", Value=1)]
      NOBODY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TIMEOUT", Value=2)]
      TIMEOUT = 2
    }
  
}