//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoChat.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_chat_base_info")]
  public partial class player_chat_base_info : global::ProtoBuf.IExtensible
  {
    public player_chat_base_info() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _headIconId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"headIconId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headIconId
    {
      get { return _headIconId; }
      set { _headIconId = value; }
    }
    private string _playerName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_realtime_voice_in")]
  public partial class req_realtime_voice_in : global::ProtoBuf.IExtensible
  {
    public req_realtime_voice_in() {}
    
    private readonly global::System.Collections.Generic.List<string> _playerId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> playerId
    {
      get { return _playerId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_realtime_voice_out")]
  public partial class req_realtime_voice_out : global::ProtoBuf.IExtensible
  {
    public req_realtime_voice_out() {}
    
    private string _channelId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_cancel_realtime_voice_in")]
  public partial class req_cancel_realtime_voice_in : global::ProtoBuf.IExtensible
  {
    public req_cancel_realtime_voice_in() {}
    
    private string _channelId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_accept_realtime_voice_in")]
  public partial class req_accept_realtime_voice_in : global::ProtoBuf.IExtensible
  {
    public req_accept_realtime_voice_in() {}
    
    private uint _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private string _channelId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_hangup_realtime_voice_in")]
  public partial class req_hangup_realtime_voice_in : global::ProtoBuf.IExtensible
  {
    public req_hangup_realtime_voice_in() {}
    
    private string _channelId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_realtime_voice_req")]
  public partial class notify_realtime_voice_req : global::ProtoBuf.IExtensible
  {
    public notify_realtime_voice_req() {}
    
    private com.sporger.server.proto.model.player_chat_base_info _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_chat_base_info player
    {
      get { return _player; }
      set { _player = value; }
    }
    private string _channelId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_realtime_voice_req_failure")]
  public partial class notify_realtime_voice_req_failure : global::ProtoBuf.IExtensible
  {
    public notify_realtime_voice_req_failure() {}
    
    private string _channelId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_player_join_realtime_voice_room")]
  public partial class notify_player_join_realtime_voice_room : global::ProtoBuf.IExtensible
  {
    public notify_player_join_realtime_voice_room() {}
    
    private com.sporger.server.proto.model.player_chat_base_info _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_chat_base_info player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_cancel_realtime_voice_req")]
  public partial class notify_cancel_realtime_voice_req : global::ProtoBuf.IExtensible
  {
    public notify_cancel_realtime_voice_req() {}
    
    private com.sporger.server.proto.model.player_chat_base_info _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_chat_base_info player
    {
      get { return _player; }
      set { _player = value; }
    }
    private string _channelId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_player_leave_realtime_voice_room")]
  public partial class notify_player_leave_realtime_voice_room : global::ProtoBuf.IExtensible
  {
    public notify_player_leave_realtime_voice_room() {}
    
    private com.sporger.server.proto.model.player_chat_base_info _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_chat_base_info player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_send_bullet_screen_in")]
  public partial class req_send_bullet_screen_in : global::ProtoBuf.IExtensible
  {
    public req_send_bullet_screen_in() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private string _content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_bullet_screen_text_out")]
  public partial class notify_bullet_screen_text_out : global::ProtoBuf.IExtensible
  {
    public notify_bullet_screen_text_out() {}
    
    private readonly global::System.Collections.Generic.List<string> _contentList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"contentList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> contentList
    {
      get { return _contentList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"voice_message_base_info")]
  public partial class voice_message_base_info : global::ProtoBuf.IExtensible
  {
    public voice_message_base_info() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _playerName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private string _headIcon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"headIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headIcon
    {
      get { return _headIcon; }
      set { _headIcon = value; }
    }
    private string _voiceId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"voiceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string voiceId
    {
      get { return _voiceId; }
      set { _voiceId = value; }
    }
    private uint _voiceSeconds = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"voiceSeconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint voiceSeconds
    {
      get { return _voiceSeconds; }
      set { _voiceSeconds = value; }
    }
    private uint _marathonId = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"marathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint marathonId
    {
      get { return _marathonId; }
      set { _marathonId = value; }
    }
    private string _marathonName = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"marathonName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string marathonName
    {
      get { return _marathonName; }
      set { _marathonName = value; }
    }
    private ulong _time = default(ulong);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _distance = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private bool _host = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool host
    {
      get { return _host; }
      set { _host = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_runner_send_voice_message_in")]
  public partial class req_runner_send_voice_message_in : global::ProtoBuf.IExtensible
  {
    public req_runner_send_voice_message_in() {}
    
    private string _voiceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"voiceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string voiceId
    {
      get { return _voiceId; }
      set { _voiceId = value; }
    }
    private uint _voiceSeconds;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"voiceSeconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint voiceSeconds
    {
      get { return _voiceSeconds; }
      set { _voiceSeconds = value; }
    }
    private uint _marathonId = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"marathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint marathonId
    {
      get { return _marathonId; }
      set { _marathonId = value; }
    }
    private uint _distance = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _fansId = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fansId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fansId
    {
      get { return _fansId; }
      set { _fansId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_runner_send_voice_message_out")]
  public partial class req_runner_send_voice_message_out : global::ProtoBuf.IExtensible
  {
    public req_runner_send_voice_message_out() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_runner_concerned_voice_message_list_in")]
  public partial class req_runner_concerned_voice_message_list_in : global::ProtoBuf.IExtensible
  {
    public req_runner_concerned_voice_message_list_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_runner_concerned_voice_message_list_out")]
  public partial class req_runner_concerned_voice_message_list_out : global::ProtoBuf.IExtensible
  {
    public req_runner_concerned_voice_message_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.voice_message_base_info> _messageList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.voice_message_base_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"messageList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.voice_message_base_info> messageList
    {
      get { return _messageList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_fans_send_voice_message_in")]
  public partial class req_fans_send_voice_message_in : global::ProtoBuf.IExtensible
  {
    public req_fans_send_voice_message_in() {}
    
    private string _runnerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"runnerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string runnerId
    {
      get { return _runnerId; }
      set { _runnerId = value; }
    }
    private string _voiceId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"voiceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string voiceId
    {
      get { return _voiceId; }
      set { _voiceId = value; }
    }
    private uint _voiceSeconds;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"voiceSeconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint voiceSeconds
    {
      get { return _voiceSeconds; }
      set { _voiceSeconds = value; }
    }
    private uint _marathonId = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"marathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint marathonId
    {
      get { return _marathonId; }
      set { _marathonId = value; }
    }
    private uint _distance = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_fans_send_voice_message_out")]
  public partial class req_fans_send_voice_message_out : global::ProtoBuf.IExtensible
  {
    public req_fans_send_voice_message_out() {}
    
    private uint _marathonId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonId
    {
      get { return _marathonId; }
      set { _marathonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_fans_voice_message_list_in")]
  public partial class req_fans_voice_message_list_in : global::ProtoBuf.IExtensible
  {
    public req_fans_voice_message_list_in() {}
    
    private uint _marathonId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonId
    {
      get { return _marathonId; }
      set { _marathonId = value; }
    }
    private uint _distance;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private string _runnerId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"runnerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string runnerId
    {
      get { return _runnerId; }
      set { _runnerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_fans_voice_message_list_out")]
  public partial class req_fans_voice_message_list_out : global::ProtoBuf.IExtensible
  {
    public req_fans_voice_message_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.voice_message_base_info> _messageList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.voice_message_base_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"messageList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.voice_message_base_info> messageList
    {
      get { return _messageList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"map_message_distance")]
  public partial class map_message_distance : global::ProtoBuf.IExtensible
  {
    public map_message_distance() {}
    
    private uint _distance;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private string _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _voiceCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"voiceCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint voiceCount
    {
      get { return _voiceCount; }
      set { _voiceCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_map_voice_message_list_in")]
  public partial class req_map_voice_message_list_in : global::ProtoBuf.IExtensible
  {
    public req_map_voice_message_list_in() {}
    
    private uint _marathonId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"marathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint marathonId
    {
      get { return _marathonId; }
      set { _marathonId = value; }
    }
    private string _runnerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"runnerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string runnerId
    {
      get { return _runnerId; }
      set { _runnerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_map_voice_message_list_out")]
  public partial class req_map_voice_message_list_out : global::ProtoBuf.IExtensible
  {
    public req_map_voice_message_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.map_message_distance> _distanceList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.map_message_distance>();
    [global::ProtoBuf.ProtoMember(1, Name=@"distanceList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.map_message_distance> distanceList
    {
      get { return _distanceList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_host_send_voice_message_in")]
  public partial class req_host_send_voice_message_in : global::ProtoBuf.IExtensible
  {
    public req_host_send_voice_message_in() {}
    
    private string _voiceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"voiceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string voiceId
    {
      get { return _voiceId; }
      set { _voiceId = value; }
    }
    private uint _voiceSeconds;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"voiceSeconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint voiceSeconds
    {
      get { return _voiceSeconds; }
      set { _voiceSeconds = value; }
    }
    private uint _marathonId = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"marathonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint marathonId
    {
      get { return _marathonId; }
      set { _marathonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_host_send_voice_message_out")]
  public partial class req_host_send_voice_message_out : global::ProtoBuf.IExtensible
  {
    public req_host_send_voice_message_out() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}