//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoRainbowRun.proto
// Note: requires additional types generated from: model/ProtoPlayer.proto
// Note: requires additional types generated from: model/ProtoBag.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"rainbowrun_player_simple_info")]
  public partial class rainbowrun_player_simple_info : global::ProtoBuf.IExtensible
  {
    public rainbowrun_player_simple_info() {}
    
    private com.sporger.server.proto.model.player_simple_info _playerInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_simple_info playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private int _colorId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"colorId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int colorId
    {
      get { return _colorId; }
      set { _colorId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_rainbowrun_matching_in")]
  public partial class req_rainbowrun_matching_in : global::ProtoBuf.IExtensible
  {
    public req_rainbowrun_matching_in() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private uint _gameType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gameType
    {
      get { return _gameType; }
      set { _gameType = value; }
    }
    private uint _time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _people;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"people", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint people
    {
      get { return _people; }
      set { _people = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_rainbowrun_matching_out")]
  public partial class notify_rainbowrun_matching_out : global::ProtoBuf.IExtensible
  {
    public notify_rainbowrun_matching_out() {}
    
    private ulong _matchingID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"matchingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong matchingID
    {
      get { return _matchingID; }
      set { _matchingID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_rainbowrun_matching_result_out")]
  public partial class notify_rainbowrun_matching_result_out : global::ProtoBuf.IExtensible
  {
    public notify_rainbowrun_matching_result_out() {}
    
    private bool _isSuc;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isSuc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isSuc
    {
      get { return _isSuc; }
      set { _isSuc = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbowrun_player_simple_info> _playerList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbowrun_player_simple_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbowrun_player_simple_info> playerList
    {
      get { return _playerList; }
    }
  
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_rainbowrun_cancel_matching_in")]
  public partial class req_rainbowrun_cancel_matching_in : global::ProtoBuf.IExtensible
  {
    public req_rainbowrun_cancel_matching_in() {}
    
    private ulong _matchingID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"matchingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong matchingID
    {
      get { return _matchingID; }
      set { _matchingID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_rainbowrun_change_track_in")]
  public partial class req_rainbowrun_change_track_in : global::ProtoBuf.IExtensible
  {
    public req_rainbowrun_change_track_in() {}
    
    private uint _desTrack;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"desTrack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint desTrack
    {
      get { return _desTrack; }
      set { _desTrack = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_rainbowrun_change_track_out")]
  public partial class req_rainbowrun_change_track_out : global::ProtoBuf.IExtensible
  {
    public req_rainbowrun_change_track_out() {}
    
    private uint _desTrack;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"desTrack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint desTrack
    {
      get { return _desTrack; }
      set { _desTrack = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_rainbowrun_change_track_out")]
  public partial class notify_rainbowrun_change_track_out : global::ProtoBuf.IExtensible
  {
    public notify_rainbowrun_change_track_out() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _desTrack;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"desTrack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint desTrack
    {
      get { return _desTrack; }
      set { _desTrack = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"rainbowrun_cur_player_info")]
  public partial class rainbowrun_cur_player_info : global::ProtoBuf.IExtensible
  {
    public rainbowrun_cur_player_info() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _area;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"area", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int area
    {
      get { return _area; }
      set { _area = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_rainbowrun_current_info_out")]
  public partial class notify_rainbowrun_current_info_out : global::ProtoBuf.IExtensible
  {
    public notify_rainbowrun_current_info_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbowrun_cur_player_info> _curPlayerInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbowrun_cur_player_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"curPlayerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbowrun_cur_player_info> curPlayerInfo
    {
      get { return _curPlayerInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"rainbow_game_result")]
  public partial class rainbow_game_result : global::ProtoBuf.IExtensible
  {
    public rainbow_game_result() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info> _rewards = new global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"rainbow_team_result")]
  public partial class rainbow_team_result : global::ProtoBuf.IExtensible
  {
    public rainbow_team_result() {}
    
    private int _rank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private int _allScore;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"allScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int allScore
    {
      get { return _allScore; }
      set { _allScore = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbow_game_result> _playerResult = new global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbow_game_result>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playerResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbow_game_result> playerResult
    {
      get { return _playerResult; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_rainbowrun_gameover_out")]
  public partial class notify_rainbowrun_gameover_out : global::ProtoBuf.IExtensible
  {
    public notify_rainbowrun_gameover_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbow_game_result> _singleRaceResult = new global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbow_game_result>();
    [global::ProtoBuf.ProtoMember(1, Name=@"singleRaceResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbow_game_result> singleRaceResult
    {
      get { return _singleRaceResult; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbow_team_result> _teamRaceResult = new global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbow_team_result>();
    [global::ProtoBuf.ProtoMember(2, Name=@"teamRaceResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.rainbow_team_result> teamRaceResult
    {
      get { return _teamRaceResult; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_rainbowrun_ready_in")]
  public partial class req_rainbowrun_ready_in : global::ProtoBuf.IExtensible
  {
    public req_rainbowrun_ready_in() {}
    
    private string _captainId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"captainId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string captainId
    {
      get { return _captainId; }
      set { _captainId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_rainbowrun_ready_out")]
  public partial class notify_rainbowrun_ready_out : global::ProtoBuf.IExtensible
  {
    public notify_rainbowrun_ready_out() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_rainbowrun_load_scene_out")]
  public partial class notify_rainbowrun_load_scene_out : global::ProtoBuf.IExtensible
  {
    public notify_rainbowrun_load_scene_out() {}
    
    private ulong _roomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private string _channelId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"room_info")]
  public partial class room_info : global::ProtoBuf.IExtensible
  {
    public room_info() {}
    
    private long _matchingID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"matchingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long matchingID
    {
      get { return _matchingID; }
      set { _matchingID = value; }
    }
    private uint _gameType = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gameType
    {
      get { return _gameType; }
      set { _gameType = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _people = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"people", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint people
    {
      get { return _people; }
      set { _people = value; }
    }
    private string _playerId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _mapId = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"room_player_info")]
  public partial class room_player_info : global::ProtoBuf.IExtensible
  {
    public room_player_info() {}
    
    private com.sporger.server.proto.model.player_simple_info _playerInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_simple_info playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private int _posId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private uint _teamId = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"function_type_info")]
  public partial class function_type_info : global::ProtoBuf.IExtensible
  {
    public function_type_info() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _btnName = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"btnName", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint btnName
    {
      get { return _btnName; }
      set { _btnName = value; }
    }
    private com.sporger.server.proto.model.FunctionType _functionType = com.sporger.server.proto.model.FunctionType.NONE;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"functionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.sporger.server.proto.model.FunctionType.NONE)]
    public com.sporger.server.proto.model.FunctionType functionType
    {
      get { return _functionType; }
      set { _functionType = value; }
    }
    private bool _agree;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_invite_friend_in")]
  public partial class req_invite_friend_in : global::ProtoBuf.IExtensible
  {
    public req_invite_friend_in() {}
    
    private long _matchingID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"matchingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long matchingID
    {
      get { return _matchingID; }
      set { _matchingID = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _playerList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> playerList
    {
      get { return _playerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_have_invite_friend_out")]
  public partial class notify_have_invite_friend_out : global::ProtoBuf.IExtensible
  {
    public notify_have_invite_friend_out() {}
    
    private long _matchingID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"matchingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long matchingID
    {
      get { return _matchingID; }
      set { _matchingID = value; }
    }
    private com.sporger.server.proto.model.player_simple_info _playerInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_simple_info playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private string _title;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private uint _time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private bool _showButton;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"showButton", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool showButton
    {
      get { return _showButton; }
      set { _showButton = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.function_type_info> _functionList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.function_type_info>();
    [global::ProtoBuf.ProtoMember(6, Name=@"functionList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.function_type_info> functionList
    {
      get { return _functionList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_agree_invite_in")]
  public partial class req_agree_invite_in : global::ProtoBuf.IExtensible
  {
    public req_agree_invite_in() {}
    
    private long _matchingID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"matchingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long matchingID
    {
      get { return _matchingID; }
      set { _matchingID = value; }
    }
    private bool _agree;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
    private string _playerId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_enter_invite_room_out")]
  public partial class notify_enter_invite_room_out : global::ProtoBuf.IExtensible
  {
    public notify_enter_invite_room_out() {}
    
    private com.sporger.server.proto.model.room_info _roomInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.room_info roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private com.sporger.server.proto.model.FunctionType _functionType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"functionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.sporger.server.proto.model.FunctionType functionType
    {
      get { return _functionType; }
      set { _functionType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_back_invite_room_out")]
  public partial class notify_back_invite_room_out : global::ProtoBuf.IExtensible
  {
    public notify_back_invite_room_out() {}
    
    private com.sporger.server.proto.model.room_info _roomInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.room_info roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.room_player_info> _playerList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.room_player_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.room_player_info> playerList
    {
      get { return _playerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_invite_friend_enter_out")]
  public partial class notify_invite_friend_enter_out : global::ProtoBuf.IExtensible
  {
    public notify_invite_friend_enter_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.room_player_info> _playerList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.room_player_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.room_player_info> playerList
    {
      get { return _playerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_rainbowrun_create_room_in")]
  public partial class req_rainbowrun_create_room_in : global::ProtoBuf.IExtensible
  {
    public req_rainbowrun_create_room_in() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_rainbowrun_create_room_out")]
  public partial class req_rainbowrun_create_room_out : global::ProtoBuf.IExtensible
  {
    public req_rainbowrun_create_room_out() {}
    
    private com.sporger.server.proto.model.room_info _roomInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.room_info roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_setting_room_in")]
  public partial class req_setting_room_in : global::ProtoBuf.IExtensible
  {
    public req_setting_room_in() {}
    
    private com.sporger.server.proto.model.room_info _roomInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.room_info roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_setting_room_out")]
  public partial class notify_setting_room_out : global::ProtoBuf.IExtensible
  {
    public notify_setting_room_out() {}
    
    private com.sporger.server.proto.model.room_info _roomInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.room_info roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_track_max_color_out")]
  public partial class notify_track_max_color_out : global::ProtoBuf.IExtensible
  {
    public notify_track_max_color_out() {}
    
    private readonly global::System.Collections.Generic.List<int> _trackColorId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"trackColorId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> trackColorId
    {
      get { return _trackColorId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"FunctionType")]
    public enum FunctionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RAINBOWRUN", Value=1)]
      RAINBOWRUN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP", Value=2)]
      PVP = 2
    }
  
}