//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoFreeRun.proto
// Note: requires additional types generated from: model/ProtoPlayer.proto
// Note: requires additional types generated from: model/ProtoRunReport.proto
// Note: requires additional types generated from: model/ProtoCheer.proto
// Note: requires additional types generated from: model/ProtoChat.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_free_run_player_start_run_time_in")]
  public partial class req_free_run_player_start_run_time_in : global::ProtoBuf.IExtensible
  {
    public req_free_run_player_start_run_time_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_free_run_player_start_run_time_out")]
  public partial class req_free_run_player_start_run_time_out : global::ProtoBuf.IExtensible
  {
    public req_free_run_player_start_run_time_out() {}
    
    private ulong _startRunTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"startRunTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong startRunTime
    {
      get { return _startRunTime; }
      set { _startRunTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_free_run_pause_in")]
  public partial class req_free_run_pause_in : global::ProtoBuf.IExtensible
  {
    public req_free_run_pause_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ulong _curTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"curTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong curTime
    {
      get { return _curTime; }
      set { _curTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_free_run_resume_in")]
  public partial class req_free_run_resume_in : global::ProtoBuf.IExtensible
  {
    public req_free_run_resume_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ulong _curTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"curTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong curTime
    {
      get { return _curTime; }
      set { _curTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_free_run_end_in")]
  public partial class req_free_run_end_in : global::ProtoBuf.IExtensible
  {
    public req_free_run_end_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_free_run_end_out")]
  public partial class req_free_run_end_out : global::ProtoBuf.IExtensible
  {
    public req_free_run_end_out() {}
    
    private com.sporger.server.proto.model.run_report_in _runReport;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"runReport", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.run_report_in runReport
    {
      get { return _runReport; }
      set { _runReport = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_free_run_info_in")]
  public partial class req_free_run_info_in : global::ProtoBuf.IExtensible
  {
    public req_free_run_info_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_free_run_info_out")]
  public partial class req_free_run_info_out : global::ProtoBuf.IExtensible
  {
    public req_free_run_info_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info> _playerIn = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerIn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info> playerIn
    {
      get { return _playerIn; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _playerOut = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playerOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> playerOut
    {
      get { return _playerOut; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_instance_syncinfo> _playersPosInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_instance_syncinfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playersPosInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_instance_syncinfo> playersPosInfo
    {
      get { return _playersPosInfo; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_remind_info> _remind = new global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_remind_info>();
    [global::ProtoBuf.ProtoMember(4, Name=@"remind", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.cheer_remind_info> remind
    {
      get { return _remind; }
    }
  
    private com.sporger.server.proto.model.voice_message_base_info _fansVoice = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fansVoice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.voice_message_base_info fansVoice
    {
      get { return _fansVoice; }
      set { _fansVoice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}