//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoLogin.proto
// Note: requires additional types generated from: model/ProtoCommon.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"login_validate_in")]
  public partial class login_validate_in : global::ProtoBuf.IExtensible
  {
    public login_validate_in() {}
    
    private string _session;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string session
    {
      get { return _session; }
      set { _session = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"login_validate_out")]
  public partial class login_validate_out : global::ProtoBuf.IExtensible
  {
    public login_validate_out() {}
    
    private int _accountLv;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accountLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int accountLv
    {
      get { return _accountLv; }
      set { _accountLv = value; }
    }
    private bool _hasCharacter;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hasCharacter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool hasCharacter
    {
      get { return _hasCharacter; }
      set { _hasCharacter = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.PBPlatformType> _bindPlatform = new global::System.Collections.Generic.List<com.sporger.server.proto.model.PBPlatformType>();
    [global::ProtoBuf.ProtoMember(3, Name=@"bindPlatform", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.PBPlatformType> bindPlatform
    {
      get { return _bindPlatform; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"login_validate_reconnect_in")]
  public partial class login_validate_reconnect_in : global::ProtoBuf.IExtensible
  {
    public login_validate_reconnect_in() {}
    
    private string _session;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string session
    {
      get { return _session; }
      set { _session = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"login_validate_reconnect_out")]
  public partial class login_validate_reconnect_out : global::ProtoBuf.IExtensible
  {
    public login_validate_reconnect_out() {}
    
    private bool _isSuccess;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isSuccess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isSuccess
    {
      get { return _isSuccess; }
      set { _isSuccess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_bind_account_in")]
  public partial class req_bind_account_in : global::ProtoBuf.IExtensible
  {
    public req_bind_account_in() {}
    
    private com.sporger.server.proto.model.PBPlatformType _bindPlatform;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bindPlatform", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.sporger.server.proto.model.PBPlatformType bindPlatform
    {
      get { return _bindPlatform; }
      set { _bindPlatform = value; }
    }
    private string _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_bind_account_out")]
  public partial class req_bind_account_out : global::ProtoBuf.IExtensible
  {
    public req_bind_account_out() {}
    
    private bool _isSuccess;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isSuccess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isSuccess
    {
      get { return _isSuccess; }
      set { _isSuccess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"account_save_info")]
  public partial class account_save_info : global::ProtoBuf.IExtensible
  {
    public account_save_info() {}
    
    private int _platformType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"platformType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int platformType
    {
      get { return _platformType; }
      set { _platformType = value; }
    }
    private string _accountName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accountName
    {
      get { return _accountName; }
      set { _accountName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}