//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoChampionship.proto
// Note: requires additional types generated from: model/ProtoBag.proto
// Note: requires additional types generated from: model/ProtoPlayer.proto
// Note: requires additional types generated from: model/ProtoRunReport.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"match_proceed_list")]
  public partial class match_proceed_list : global::ProtoBuf.IExtensible
  {
    public match_proceed_list() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _crowd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"crowd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint crowd
    {
      get { return _crowd; }
      set { _crowd = value; }
    }
    private uint _tabId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tabId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tabId
    {
      get { return _tabId; }
      set { _tabId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_match_proceed_list_in")]
  public partial class req_match_proceed_list_in : global::ProtoBuf.IExtensible
  {
    public req_match_proceed_list_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_match_proceed_list_out")]
  public partial class req_match_proceed_list_out : global::ProtoBuf.IExtensible
  {
    public req_match_proceed_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.match_proceed_list> _matchProceedList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.match_proceed_list>();
    [global::ProtoBuf.ProtoMember(1, Name=@"matchProceedList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.match_proceed_list> matchProceedList
    {
      get { return _matchProceedList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_match_map_in")]
  public partial class req_enter_match_map_in : global::ProtoBuf.IExtensible
  {
    public req_enter_match_map_in() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_match_map_out")]
  public partial class req_enter_match_map_out : global::ProtoBuf.IExtensible
  {
    public req_enter_match_map_out() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private ulong _roomId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _distance = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"season_rank_info")]
  public partial class season_rank_info : global::ProtoBuf.IExtensible
  {
    public season_rank_info() {}
    
    private uint _seasonId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seasonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seasonId
    {
      get { return _seasonId; }
      set { _seasonId = value; }
    }
    private uint _place;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"place", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint place
    {
      get { return _place; }
      set { _place = value; }
    }
    private uint _integral;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"integral", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint integral
    {
      get { return _integral; }
      set { _integral = value; }
    }
    private uint _grade;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"season_player_info")]
  public partial class season_player_info : global::ProtoBuf.IExtensible
  {
    public season_player_info() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private com.sporger.server.proto.model.player_simple_info _playerInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_simple_info playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private uint _grade;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private uint _currentIntegral;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"currentIntegral", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint currentIntegral
    {
      get { return _currentIntegral; }
      set { _currentIntegral = value; }
    }
    private uint _cityId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cityId
    {
      get { return _cityId; }
      set { _cityId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_season_rank_list_in")]
  public partial class req_season_rank_list_in : global::ProtoBuf.IExtensible
  {
    public req_season_rank_list_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_season_rank_list_out")]
  public partial class req_season_rank_list_out : global::ProtoBuf.IExtensible
  {
    public req_season_rank_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.season_player_info> _currentRank = new global::System.Collections.Generic.List<com.sporger.server.proto.model.season_player_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"currentRank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.season_player_info> currentRank
    {
      get { return _currentRank; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.season_rank_info> _historySeason = new global::System.Collections.Generic.List<com.sporger.server.proto.model.season_rank_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"historySeason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.season_rank_info> historySeason
    {
      get { return _historySeason; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.season_player_info> _playerRank = new global::System.Collections.Generic.List<com.sporger.server.proto.model.season_player_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playerRank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.season_player_info> playerRank
    {
      get { return _playerRank; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_season_player_list_in")]
  public partial class req_season_player_list_in : global::ProtoBuf.IExtensible
  {
    public req_season_player_list_in() {}
    
    private uint _seasonId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seasonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seasonId
    {
      get { return _seasonId; }
      set { _seasonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_season_player_list_out")]
  public partial class req_season_player_list_out : global::ProtoBuf.IExtensible
  {
    public req_season_player_list_out() {}
    
    private com.sporger.server.proto.model.season_rank_info _seasonInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seasonInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.season_rank_info seasonInfo
    {
      get { return _seasonInfo; }
      set { _seasonInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.season_player_info> _playerList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.season_player_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.season_player_info> playerList
    {
      get { return _playerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_have_match_start_out")]
  public partial class notify_have_match_start_out : global::ProtoBuf.IExtensible
  {
    public notify_have_match_start_out() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_season_start_in")]
  public partial class req_season_start_in : global::ProtoBuf.IExtensible
  {
    public req_season_start_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_season_start_out")]
  public partial class notify_season_start_out : global::ProtoBuf.IExtensible
  {
    public notify_season_start_out() {}
    
    private uint _seasonId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seasonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seasonId
    {
      get { return _seasonId; }
      set { _seasonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_grade_change_out")]
  public partial class notify_grade_change_out : global::ProtoBuf.IExtensible
  {
    public notify_grade_change_out() {}
    
    private uint _currentGrade;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"currentGrade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint currentGrade
    {
      get { return _currentGrade; }
      set { _currentGrade = value; }
    }
    private bool _isUp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isUp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isUp
    {
      get { return _isUp; }
      set { _isUp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_season_integral_in")]
  public partial class req_season_integral_in : global::ProtoBuf.IExtensible
  {
    public req_season_integral_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_season_integral_out")]
  public partial class req_season_integral_out : global::ProtoBuf.IExtensible
  {
    public req_season_integral_out() {}
    
    private uint _integral;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"integral", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint integral
    {
      get { return _integral; }
      set { _integral = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"champion_curent_index")]
  public partial class champion_curent_index : global::ProtoBuf.IExtensible
  {
    public champion_curent_index() {}
    
    private string _nickName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private uint _distance;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private uint _rank;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private string _playerId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _nickIcon;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"nickIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickIcon
    {
      get { return _nickIcon; }
      set { _nickIcon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_champion_curent_info_out")]
  public partial class notify_champion_curent_info_out : global::ProtoBuf.IExtensible
  {
    public notify_champion_curent_info_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.champion_curent_index> _curInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.champion_curent_index>();
    [global::ProtoBuf.ProtoMember(1, Name=@"curInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.champion_curent_index> curInfo
    {
      get { return _curInfo; }
    }
  
    private uint _playerCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private uint _audienceCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"audienceCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint audienceCount
    {
      get { return _audienceCount; }
      set { _audienceCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_champion_gameover_out")]
  public partial class notify_champion_gameover_out : global::ProtoBuf.IExtensible
  {
    public notify_champion_gameover_out() {}
    
    private com.sporger.server.proto.model.run_report_in _runInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"runInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.run_report_in runInfo
    {
      get { return _runInfo; }
      set { _runInfo = value; }
    }
    private bool _isFinished;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isFinished", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFinished
    {
      get { return _isFinished; }
      set { _isFinished = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"champion_player_rank_info")]
  public partial class champion_player_rank_info : global::ProtoBuf.IExtensible
  {
    public champion_player_rank_info() {}
    
    private uint _rankId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rankId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankId
    {
      get { return _rankId; }
      set { _rankId = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _finishTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"finishTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint finishTime
    {
      get { return _finishTime; }
      set { _finishTime = value; }
    }
    private uint _countryId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"countryId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint countryId
    {
      get { return _countryId; }
      set { _countryId = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"watch_match_result")]
    public enum watch_match_result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOERROR", Value=0)]
      NOERROR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOBODY", Value=1)]
      NOBODY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TIMEOUT", Value=2)]
      TIMEOUT = 2
    }
  
}